### ISSUE TITLE
Timeout issue when launching waves-0.3.6 on macOS Sierra

### ISSUE THREAD

**Issue by PyWaves** [wavesplatform/Waves#104]
Launching waves-0.3.6 on macOS Sierra produces the following output and the process dies:

$ java -jar waves-0.3.6.jar waves-mainnet.json
[WARN] [12/27/2016 09:11:41.987] [main] [EventStream(akka://wavesplatform)] Logger log1-Slf4jLogger did not respond within Timeout(5000 milliseconds) to InitializeLogger(bus)
error while starting up loggers
akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:119)
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:118)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Failure.recover(Try.scala:216)
	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:118)
	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:113)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:683)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:682)
	at akka.event.LoggingBus$class.startDefaultLoggers(Logging.scala:113)
	at akka.event.EventStream.startDefaultLoggers(EventStream.scala:28)
	at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:667)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:657)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:654)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:654)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:670)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
	at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:22)
	at com.wavesplatform.Application$.main(Application.scala:81)
	at com.wavesplatform.Application.main(Application.scala)
Caused by: akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]
	at akka.event.LoggingBus$class.akka$event$LoggingBus$$addLogger(Logging.scala:188)
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$4.apply(Logging.scala:117)
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$4.apply(Logging.scala:116)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:116)
	... 19 more
Exception in thread "main" akka.ConfigurationException: Could not start logger due to [akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]]
	at akka.event.LoggingBus$class.startDefaultLoggers(Logging.scala:147)
	at akka.event.EventStream.startDefaultLoggers(EventStream.scala:28)
	at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:667)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:657)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:654)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:654)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:670)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
	at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:22)
	at com.wavesplatform.Application$.main(Application.scala:81)
	at com.wavesplatform.Application.main(Application.scala)
2016-12-27 09:11:42 INFO  [lt-dispatcher-4] a.event.slf4j.Slf4jLogger - Slf4jLogger started

I have been able to reproduce the issue on different macs with macOS Sierra. I don’t know if this problem also occurs with previous version of OS X. 
Increasing ‘logger-startup-timeout’ from 5 seconds to 10 seconds in reference.conf seems to solve the problem.

**Comment by mikeolteanu** [comment]
if you want to modify the reference.conf file, you need to unpack the jar file, edit the config and rebuild the jar, this way:

cd ~/waves (or the folder where waves-0.3.6.jar is located)
mkdir tmp
cd tmp
jar xf ../waves-0.3.6.jar

edit reference.conf and increase logger-startup-timeout to 10s

jar cfM ../waves-0.3.6.jar .
cd ..
rm -rf tmp
