### ISSUE TITLE
Orders with spendAssetId == receiveAssetId cause the node to crash

### ISSUE THREAD

**Issue by PyWaves** [wavesplatform/Waves#109]
Posting an order with spendAssetId equal to receiveAssetId causes the matcher and the node to crash with the following output:

2017-01-15 07:23:02 ERROR [t-dispatcher-26] c.w.actor.RootActorSystem$ - Root actor got exception, escalate
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)
	at scorex.transaction.assets.exchange.AssetPair.<init>(AssetPair.scala:8)
	at scorex.transaction.assets.exchange.Order.assetPair(Order.scala:43)
	at com.wavesplatform.matcher.market.MatcherActor$$anonfun$forwardToOrderBook$1.applyOrElse(MatcherActor.scala:55)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
	at com.wavesplatform.matcher.market.MatcherActor.akka$persistence$Eventsourced$$super$aroundReceive(MatcherActor.scala:25)
	at akka.persistence.Eventsourced$$anon$1.stateReceive(Eventsourced.scala:664)
	at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:183)
	at com.wavesplatform.matcher.market.MatcherActor.aroundReceive(MatcherActor.scala:25)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2017-01-15 07:23:02 ERROR [t-dispatcher-23] a.a.LocalActorRefProvider(akka://wavesplatform) - guardian failed, shutting down system
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)
	at scorex.transaction.assets.exchange.AssetPair.<init>(AssetPair.scala:8)
	at scorex.transaction.assets.exchange.Order.assetPair(Order.scala:43)
	at com.wavesplatform.matcher.market.MatcherActor$$anonfun$forwardToOrderBook$1.applyOrElse(MatcherActor.scala:55)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
	at com.wavesplatform.matcher.market.MatcherActor.akka$persistence$Eventsourced$$super$aroundReceive(MatcherActor.scala:25)
	at akka.persistence.Eventsourced$$anon$1.stateReceive(Eventsourced.scala:664)
	at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:183)
	at com.wavesplatform.matcher.market.MatcherActor.aroundReceive(MatcherActor.scala:25)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2017-01-15 07:23:02 ERROR [t-dispatcher-23] a.actor.OneForOneStrategy - requirement failed
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)
	at scorex.transaction.assets.exchange.AssetPair.<init>(AssetPair.scala:8)
	at scorex.transaction.assets.exchange.Order.assetPair(Order.scala:43)
	at com.wavesplatform.matcher.market.MatcherActor$$anonfun$forwardToOrderBook$1.applyOrElse(MatcherActor.scala:55)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
	at com.wavesplatform.matcher.market.MatcherActor.akka$persistence$Eventsourced$$super$aroundReceive(MatcherActor.scala:25)
	at akka.persistence.Eventsourced$$anon$1.stateReceive(Eventsourced.scala:664)
	at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:183)
	at com.wavesplatform.matcher.market.MatcherActor.aroundReceive(MatcherActor.scala:25)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

I don't see a case where spendAssetId needs to be equal to receiveAssetId, so maybe spendAssetId != receiveAssetId should be added to the order validation rules.

**Comment by koloale** [comment]
Fixed on Testnet.
