### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by Alteryy** [wavesplatform/Waves#1512]
Sep 27 10:30:43 waves[1954]: INFO  c.w.Application$ - Starting...
Sep 27 10:30:44 waves[1954]: Exception in thread "main" java.lang.ExceptionInInitializerError
Sep 27 10:30:44 waves[1954]:         at com.wavesplatform.mining.Miner$.<init>(Miner.scala:357)
Sep 27 10:30:44 waves[1954]:         at com.wavesplatform.mining.Miner$.<clinit>(Miner.scala)
Sep 27 10:30:44 waves[1954]:         at com.wavesplatform.settings.MinerSettings.<init>(MinerSettings.scala:16)
Sep 27 10:30:44 waves[1954]:         at com.wavesplatform.settings.MinerSettings$.fromConfig(MinerSettings.scala:45)
Sep 27 10:30:44 waves[1954]:         at com.wavesplatform.settings.WavesSettings$.fromConfig(WavesSettings.scala:41)
Sep 27 10:30:44 waves[1954]:         at com.wavesplatform.Application$.main(Application.scala:421)
Sep 27 10:30:44 waves[1954]:         at com.wavesplatform.Application.main(Application.scala)
Sep 27 10:30:44 waves[1954]: Caused by: java.net.UnknownHostException: iZt4n1ut6ttmc6s15c9xrrZ: iZt4n1ut6ttmc6s15c9xrrZ: Name or service not known
Sep 27 10:30:44 waves[1954]:         at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
Sep 27 10:30:44 waves[1954]:         at kamon.Environment$.$anonfun$fromConfig$2(Environment.scala:37)
Sep 27 10:30:44 waves[1954]:         at kamon.Environment$.readValueOrGenerate(Environment.scala:49)
Sep 27 10:30:44 waves[1954]:         at kamon.Environment$.fromConfig(Environment.scala:37)
Sep 27 10:30:44 waves[1954]:         at kamon.Kamon$.<init>(Kamon.scala:36)
Sep 27 10:30:44 waves[1954]:         at kamon.Kamon$.<clinit>(Kamon.scala)
Sep 27 10:30:44 waves[1954]:         ... 7 more
Sep 27 10:30:44 waves[1954]: Caused by: java.net.UnknownHostException: iZt4n1ut6ttmc6s15c9xrrZ: Name or service not known
Sep 27 10:30:44 waves[1954]:         at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
Sep 27 10:30:44 waves[1954]:         at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
Sep 27 10:30:44 waves[1954]:         at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
Sep 27 10:30:44 waves[1954]:         at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
Sep 27 10:30:44 waves[1954]:         ... 12 more
Sep 27 10:30:44 systemd[1]: waves.service: Main process exited, code=exited, status=1/FAILURE
Sep 27 10:30:44 systemd[1]: waves.service: Unit entered failed state.
Sep 27 10:30:44 systemd[1]: waves.service: Failed with result 'exit-code'.

The server is not working properly after the upgrade.

**Comment by Alteryy** [comment]
sudo -u waves importer /etc/waves/waves.conf /usr/share/waves/mainnet-1198102
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.wavesplatform.mining.Miner$.<init>(Miner.scala:357)
	at com.wavesplatform.mining.Miner$.<clinit>(Miner.scala)
	at com.wavesplatform.settings.MinerSettings.<init>(MinerSettings.scala:16)
	at com.wavesplatform.settings.MinerSettings$.fromConfig(MinerSettings.scala:45)
	at com.wavesplatform.settings.WavesSettings$.fromConfig(WavesSettings.scala:41)
	at com.wavesplatform.Importer$.main(Importer.scala:33)
	at com.wavesplatform.Importer.main(Importer.scala)
Caused by: java.net.UnknownHostException: iZt4n1ut6ttmc6s15c9xrrZ: iZt4n1ut6ttmc6s15c9xrrZ: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at kamon.Environment$.$anonfun$fromConfig$2(Environment.scala:37)
	at kamon.Environment$.readValueOrGenerate(Environment.scala:49)
	at kamon.Environment$.fromConfig(Environment.scala:37)
	at kamon.Kamon$.<init>(Kamon.scala:36)
	at kamon.Kamon$.<clinit>(Kamon.scala)
	... 7 more
Caused by: java.net.UnknownHostException: iZt4n1ut6ttmc6s15c9xrrZ: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	... 12 more

**Comment by monroid** [comment]
Hi @Alteryy,
from what version of node did you try to update? you were trying an import of blockchain, config file was the same?

**Comment by vsuharnikov** [comment]
@Alteryy Try to add:
```
kamon.enable = no
metrics.enable = no
```
at the end of configuration file and run this again :)
