### ISSUE TITLE
NODE WAS STOPPED AUTOMATICALLY

### ISSUE THREAD

**Issue by pelitlik** [wavesplatform/Waves#1793]
Hello,

I faced following error: I use Waves v0.14.7 verison.

`ERROR c.w.s.BlockchainUpdaterImpl - UNIMPLEMENTED FEATURES 10, 9 have been ACTIVATED ON BLOCKCHAIN
ERROR c.w.s.BlockchainUpdaterImpl - PLEASE, UPDATE THE NODE IMMEDIATELY
ERROR c.w.s.BlockchainUpdaterImpl - FOR THIS REASON THE NODE WAS STOPPED AUTOMATICALLY
INFO  c.w.s.BlockchainUpdaterImpl - New height: 1340000
INFO  c.w.utils.TimeImpl - Shutting down Time
INFO  c.w.Application - HistoryReplier was shutdown successfully
INFO  c.w.Application - Closing REST API
INFO  c.w.n.PeerDatabaseImpl - Saving 185 known peer(s) to peers.dat
Exception in thread "shutdownHook3" java.io.FileNotFoundException: /var/lib/waves/peers.dat (Permission denied)
at java.io.FileOutputStream.open0(java.base@9-internal/Native Method)
at java.io.FileOutputStream.open(java.base@9-internal/FileOutputStream.java:271)
at java.io.FileOutputStream.<init>(java.base@9-internal/FileOutputStream.java:215)
at java.io.FileOutputStream.<init>(java.base@9-internal/FileOutputStream.java:104)
at java.io.PrintWriter.<init>(java.base@9-internal/PrintWriter.java:176)
at com.wavesplatform.utils.JsonFileStorage$.save(JsonFileStorage.scala:59)
at com.wavesplatform.utils.JsonFileStorage$.save(JsonFileStorage.scala:71)
at com.wavesplatform.network.PeerDatabaseImpl.$anonfun$close$1(PeerDatabaseImpl.scala:131)
at com.wavesplatform.network.PeerDatabaseImpl.$anonfun$close$1$adapted(PeerDatabaseImpl.scala:124)
at scala.Option.foreach(Option.scala:257)
at com.wavesplatform.network.PeerDatabaseImpl.close(PeerDatabaseImpl.scala:124)
at com.wavesplatform.Application.shutdown(Application.scala:321)
at com.wavesplatform.Application.$anonfun$run$19(Application.scala:295)
at scala.sys.ShutdownHookThread$$anon$1.run(ShutdownHookThread.scala:34)
waves.service: Main process exited, code=exited, status=38/n/a
waves.service: Unit entered failed state.
waves.service: Failed with result 'exit-code'.`

**Comment by monroid** [comment]
@pelitlik hi!
please, update your node to the newest version 0.15.4.
