### ISSUE TITLE
File Corrupted after restarting a node

### ISSUE THREAD

**Issue by deepred86** [wavesplatform/Waves#205]
I'm using lastest mainnet 0.3.9 on a RaspberryPi3 
data dir is on a ext4 usb key and it's running fine till I close the node, reboot and restart, it gives me this error:

java.lang.IllegalStateException: File corrupted in chunk 156855, expected page length 4..384, got 537067732 [1.4.193/6]

The solution is removing blockchain file and restart from scratch, and that's madness, is there anything else I could try in order to fix it?

**Comment by deepred86** [comment]
This is the full waves command execution output

`Java HotSpot(TM) Server VM warning: G1 GC is disabled in this release.
2017-03-23 14:15:59 INFO  [lt-dispatcher-4] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2017-03-23 14:15:59 INFO  [main] c.w.Application$ - Starting with args: [/etc/waves.json] 
2017-03-23 14:16:06 INFO  [main] c.w.Application$ - Waves - Release0 v0.3.9 Blockchain Id: 87
2017-03-23 14:16:07 ERROR [main] c.w.actor.RootActorSystem$ - Error while initializing actor system wavesplatform
java.lang.IllegalStateException: File corrupted in chunk 156855, expected page length 4..384, got 537067732 [1.4.193/6]

	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.Page.read(Page.java:649)
	at org.h2.mvstore.Page.read(Page.java:195)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:1954)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:736)
	at org.h2.mvstore.Page.getChildPage(Page.java:217)
	at org.h2.mvstore.Cursor.fetchNext(Cursor.java:150)
	at org.h2.mvstore.Cursor.next(Cursor.java:50)
	at org.h2.mvstore.MVStore.loadChunkMeta(MVStore.java:696)
	at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:676)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:359)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2923)
	at scorex.transaction.state.database.BlockStorageImpl.createMVStore(BlockStorageImpl.scala:22)
	at scorex.transaction.state.database.BlockStorageImpl.<init>(BlockStorageImpl.scala:17)
	at scorex.transaction.SimpleTransactionModule.<init>(SimpleTransactionModule.scala:60)
	at scorex.waves.transaction.WavesTransactionModule.<init>(WavesTransactionModule.scala:21)

	at com.wavesplatform.Application.transactionModule$lzycompute(Application.scala:32)
	at com.wavesplatform.Application.transactionModule(Application.scala:32)
	at com.wavesplatform.Application.<init>(Application.scala:73)
	at com.wavesplatform.Application$$anonfun$main$1.apply(Application.scala:93)
	at com.wavesplatform.Application$$anonfun$main$1.apply(Application.scala:81)
	at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:30)
	at com.wavesplatform.Application$.main(Application.scala:81)
	at com.wavesplatform.Application.main(Application.scala)

2017-03-23 14:16:07 INFO  [lt-dispatcher-4] s.n.NetworkController - Declared address: None
`

**Comment by alexeykiselev** [comment]
We've submitted this problem as a bug to MVStore developers. You could up vote for this bug using link that @Tolsi posted earlier.
