### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by br0x** [wavesplatform/Waves#2440]
_These started today (strange coincidence with ride activation?):_

2019-07-11 10:07:12,449 INFO  [appender-44] c.w.s.BlockchainUpdaterImpl - New height: 1610708
2019-07-11 10:07:12,452 WARN  [appender-44] k.m.AtomicHdrHistogram - Failed to record value [133677838900] in histogram [block-appender.blockchain-append-block]. You might need to change your dynamic range configuration for this instrument.
java.lang.ArrayIndexOutOfBoundsException: value 133677838900 outside of histogram covered range. Caused by: java.lang.IndexOutOfBoundsException: index 287
        at org.HdrHistogram.AbstractHistogram.handleRecordException(AbstractHistogram.java:537)
        at org.HdrHistogram.AbstractHistogram.recordCountAtValue(AbstractHistogram.java:516)
        at org.HdrHistogram.AbstractHistogram.recordValueWithCount(AbstractHistogram.java:441)
        at kamon.metric.AtomicHdrHistogram.tryRecord(Histogram.scala:48)
        at kamon.metric.AtomicHdrHistogram.record(Histogram.scala:38)
        at kamon.metric.HistogramMetricImpl.record(Metric.scala:101)
        at kamon.metric.StartedTimer$$anon$1.stop(Timer.scala:36)
        at com.wavesplatform.state.appender.package$.appendBlock(package.scala:92)
        at com.wavesplatform.state.appender.package$.$anonfun$appendBlock$9(package.scala:87)
        at com.wavesplatform.state.appender.package$.$anonfun$appendBlock$5(package.scala:79)
        at com.wavesplatform.state.appender.package$.appendBlock(package.scala:74)
        at com.wavesplatform.state.appender.ExtensionAppender$.$anonfun$apply$6(ExtensionAppender.scala:46)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
        at scala.collection.Iterator$$anon$18.next(Iterator.scala:849)
        at scala.collection.Iterator$$anon$18.next(Iterator.scala:847)
        at scala.collection.TraversableOnce.collectFirst(TraversableOnce.scala:148)
        at scala.collection.TraversableOnce.collectFirst$(TraversableOnce.scala:135)
        at scala.collection.SeqViewLike$AbstractTransformed.collectFirst(SeqViewLike.scala:40)
        at com.wavesplatform.state.appender.ExtensionAppender$.$anonfun$apply$5(ExtensionAppender.scala:52)
        at monix.eval.Coeval$Always.apply(Coeval.scala:1136)
        at com.wavesplatform.state.appender.ExtensionAppender$.$anonfun$apply$18(ExtensionAppender.scala:85)
        at com.wavesplatform.state.appender.ExtensionAppender$.$anonfun$apply$2(ExtensionAppender.scala:83)
        at com.wavesplatform.state.appender.ExtensionAppender$.$anonfun$apply$1(ExtensionAppender.scala:37)
        at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:76)
        at monix.eval.internal.TaskRunLoop$RestartCallback.onSuccess(TaskRunLoop.scala:537)
        at monix.eval.Task$$anon$3.run(Task.scala:2161)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by kolte** [comment]
I am having the same issue, any solution please?

**Comment by disfenoid** [comment]
It happens because we have changed metrics settings to decrease memory footprint. This affects only metrics, so you can just ignore these messages.

**Comment by phearnot** [comment]
This has been fixed in #2509.
