### ISSUE TITLE
matcher node error

### ISSUE THREAD

**Issue by hbastidas** [wavesplatform/Waves#2452]
hello, I'm trying to run a matcher node to create a dex and I hope to result in something like 
https://matcher.wavesplatform.com/api-docs/index.html

but by adding something like this in the config
`
  extensions = [
    com.wavesplatform.dex.Matcher
    # com.wavesplatform.api.grpc.GRPCServerExtension
  ]

  dex {
    account = "3EnATnxW9b45RUXmvBvC5mrW3LGcENMB7nm" # This account must be known at the Node, e.g. created through POST /addresses
    # bind-address = "0.0.0.0" # uncomment this line to accept connections from any host
  }
`

compiling "packageAll" and running it like this

`macos:Waves hbastidas$ java --add-modules=java.xml.bind --add-exports java.base/jdk.internal.ref=ALL-UNNAMED -jar node/target/waves-all*.jar /Users/hbastidas/projects/Waves/node/mydevnet.conf`

I've got something like this.

`2019-07-17 15:38:32,850 INFO  [main] c.w.Application$ - Starting...
2019-07-17 15:38:33,104 INFO  [ctor.default-dispatcher-3] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2019-07-17 15:38:33,144 INFO  [main] c.w.Application$ - Waves v1.0.0-DIRTY Blockchain Id: B
2019-07-17 15:38:34,920 INFO  [main] c.w.n.PeerDatabaseImpl - Loaded 0 known peer(s) from peers.dat
2019-07-17 15:38:35,394 INFO  [main] com.wavesplatform.package$ - Genesis block Block(4VSkSnUR55yepgZs2ov45hMbPjmhaDknh7ymDsa4oZkyaHhjWgWbU7Mt5BVzWe3dc13TjpAYmjCp8UncjWG2QYgH -> 67rpwLC..., txs=2, features=Set()) has been added to the state
2019-07-17 15:38:35,574 ERROR [main] c.w.actor.RootActorSystem$ - Error while initializing actor system wavesplatform
java.lang.ClassNotFoundException: com.wavesplatform.dex.Matcher
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:291)
	at com.wavesplatform.Application.$anonfun$run$13(Application.scala:227)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at com.wavesplatform.Application.run(Application.scala:226)
	at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:447)
	at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:426)
	at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
	at com.wavesplatform.Application$.startNode(Application.scala:426)
	at com.wavesplatform.Application$.main(Application.scala:409)
	at com.wavesplatform.Application.main(Application.scala)`

Is there any more explanatory documentation of this process?
If necessary I can help you document but I must know how you do this.

**Comment by vsuharnikov** [comment]
Hi! The DEX is in a separate repository now: https://github.com/wavesplatform/dex Here you will find instructions how to run NODE with DEX

**Comment by cryptoneobancoin** [comment]
bro thaat dosent help us

**Comment by username1565** [comment]
@vsuharnikov, as I understand, this is extension for the nodes with last versions v1.0.1 and v1.0.2.
And this extension must be runned with node, as different application, like [WAVES DATAFEED API](https://github.com/PyWaves/WavesDataFeed), right?

But I don't see any compiled JAR-file for windows, here: https://github.com/wavesplatform/dex/releases

I just see MATCHER REST API working for node with version v0.17.1, but there need to re-synchronize blockchain.
