### ISSUE TITLE
[BUG] No auto-repair for damaged blockchain database.

### ISSUE THREAD

**Issue by username1565** [wavesplatform/Waves#2621]
**If this problem can be solved by another way, without resynchronize full blockchain -
tell me please about - how to solve this.**

**Describe the bug**
>A clear and concise description of what the bug is.

Node not starting after shut-down after spontaneous power off.

**To Reproduce**
>Steps to reproduce the behavior:

1. Go to 'power button'
2. Click on 'shut-down the power'
3. after damage the database, run the node, and Scroll down to 'the bottom'
4. See error.

**Expected behavior**
>A clear and concise description of what you expected to happen.

Automatic rollback to the last correct block, removal of damaged blocks, and synchronization the last blocks of the actual blockchain, and auto-repair the damaged database.

**Screenshots**
>If applicable, add screenshots to help explain your problem.

Console throw error:
```
2019-09-22 00:07:58,019 ERROR [main] c.w.actor.RootActorSystem$ -
Error while initializing actor system wavesplatformorg.iq80.leveldb.DBException:
Corruption: not an sstable (bad magic number)
        at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:153)
        at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:114)
        at com.wavesplatform.history.StorageFactory$.checkVersion(StorageFactory.scala:21)
        at com.wavesplatform.history.StorageFactory$.apply(StorageFactory.scala:16)
        at com.wavesplatform.Application.(Application.scala:70)
        at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:440)
        at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:419)
        at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
        at com.wavesplatform.Application$.startNode(Application.scala:419)
        at com.wavesplatform.Application$.main(Application.scala:402)
        at com.wavesplatform.Application.main(Application.scala)
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption:not an sstable (bad magic number)
        at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
        at org.fusesource.leveldbjni.internal.NativeDB.write(NativeDB.java:285)
        at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:150)
        ... 10 common frames omitted
```
Node cann't starting after this, and after restart. I see this error again and again...

**Desktop (please complete the following information):**
 - OS: [e.g. Debian/Ubuntu/iOS] - Windows
 - Browser/JVM [e.g. chrome, safari] - Google Chrome
 - Version [e.g. 22] - jar-file with node v1.0.2

**Additional context**
>Add any other context about the problem here.

Need to program auto-repair for damaged database of blockchain, when this database is damaged.
For example, if database is damaged, then fast re-scan old blockchain, up to latest valid block,
then remove last damaged blocks, and re-synchronize from last valid block.
This can be runned after several restarts of the program.

**Comment by username1565** [comment]
Damaged blockchain, you can see on this screen: 
![damaged_blockchain](https://user-images.githubusercontent.com/39200328/65380744-9f9f8380-dcea-11e9-8058-b811bb715591.jpg)

As you can see, there is does not exists all files, from 7264504 - up to 7264535.
Maybe, need to make writting something data, only after this files already exists, not before.

**Comment by username1565** [comment]
You can add inside the node something tools, like this: https://antimatter15.com/2015/12/recovering-deleted-data-from-leveldb/
to recovery the damaged database.
For example: `java -jar waves-all-1.1.2.jar -recover_leveldb`

**Comment by username1565** [comment]
I already found the solution, in the case of damage database or/and corrupt data in the database.
This solution is just copy the folder `data` from `previous copied backup`, and synchronize the rest of `blockchain`.
In the case of importing block from unpacked `.tar`[-archive](http://blockchain.wavesnodes.com/),
anyway need to wait the slow again importing blockchain, and verifying ALL blocks `FROM BEGINNING AND TO END` to do this importing.
But if folder just will be copied to `backup`, after successfull import blockchain and verify all blocks inside,
in this case, after restore this `backup` - no need to verify blocks again, and this working without again importing blocks.

After all, if you don't want to programming any tools to do restore the corrupted leveldb database,
you can just add some notification for user, after full syncrhonization,
to stimulate him a make `backup` a `folder with blockchain database`.
Because in some cases need to restore blockchain,
but this is impossible, without the slow - FULL re-synchronization...

This issue is closed just because solution was been found.
But you can think about it all.

Best regards.
