### ISSUE TITLE
1.1.4 WARN UtxPoolSynchronizerImpl - Error validating transaction

### ISSUE THREAD

**Issue by br0x** [wavesplatform/Waves#2686]
_Many warnings like this:_
```
WARN  c.w.n.UtxPoolSynchronizerImpl - Error validating transaction HY1ztKpPethKnemejyFWuG6vrvrgP3m1mapBZJbg8wyG
java.lang.IllegalMonitorStateException: attempt to unlock read lock, not locked by current thread
        at java.base/java.util.concurrent.locks.ReentrantReadWriteLock$Sync.unmatchedUnlockException(ReentrantReadWriteLock.java:448)
        at java.base/java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryReleaseShared(ReentrantReadWriteLock.java:432)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.releaseShared(AbstractQueuedSynchronizer.java:1382)
        at java.base/java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.unlock(ReentrantReadWriteLock.java:897)
        at com.wavesplatform.state.BlockchainUpdaterImpl.hasScript(BlockchainUpdaterImpl.scala:51)
        at com.wavesplatform.utx.UtxPoolImpl$TxCheck$.isScripted(UtxPoolImpl.scala:267)
        at com.wavesplatform.utx.UtxPoolImpl$LimitChecks$1$.$anonfun$checkScripted$1(UtxPoolImpl.scala:81)
        at com.wavesplatform.utx.UtxPoolImpl$LimitChecks$1$.checkScripted(UtxPoolImpl.scala:80)
        at com.wavesplatform.utx.UtxPoolImpl.$anonfun$putNewTx$8(UtxPoolImpl.scala:147)
        at com.wavesplatform.utx.UtxPoolImpl.$anonfun$putNewTx$5(UtxPoolImpl.scala:141)
        at com.wavesplatform.utx.UtxPoolImpl.$anonfun$putNewTx$1(UtxPoolImpl.scala:140)
        at com.wavesplatform.utx.UtxPoolImpl.putNewTx(UtxPoolImpl.scala:65)
        at com.wavesplatform.utx.UtxPoolImpl.putIfNew(UtxPoolImpl.scala:59)
        at com.wavesplatform.network.UtxPoolSynchronizer$.$anonfun$apply$1(UtxPoolSynchronizer.scala:88)
        at com.wavesplatform.network.UtxPoolSynchronizerImpl.$anonfun$validateFuture$1(UtxPoolSynchronizer.scala:63)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at monix.execution.internal.InterceptRunnable.run(InterceptRunnable.scala:27)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at com.wavesplatform.utils.Schedulers$TimedWrapper.run(Schedulers.scala:95)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by phearnot** [comment]
Fixed in #2696
