### ISSUE TITLE
Crash in Appender

### ISSUE THREAD

**Issue by br0x** [wavesplatform/Waves#2792]
This crash happened several times, on different architectures
```
2019-12-04 23:27:26,112 INFO  [appender-44] c.w.s.BlockchainUpdaterImpl - MicroBlock(4DvNNgt... -> 2H9zaTR..., txs=5) appended
2019-12-04 23:27:33,010 INFO  [appender-44] c.w.s.BlockchainUpdaterImpl - MicroBlock(5uSC9EG... -> 4DvNNgt..., txs=5) appended
2019-12-04 23:27:37,576 DEBUG [rx-extension-loader-39] c.w.n.RxExtensionLoader$ - [01ce79bc 35.156.19.4:6868] Requesting signatures, last 100 are (total=100) [5uSC9EG... -- 3iWY9YE...]
2019-12-04 23:27:37,605 DEBUG [rx-extension-loader-39] c.w.n.RxExtensionLoader$ - [01ce79bc 35.156.19.4:6868] ExtensionBlocks([45TRrXn...] successfully received
2019-12-04 23:27:37,605 DEBUG [rx-extension-loader-39] c.w.n.RxExtensionLoader$ - [01ce79bc 35.156.19.4:6868] Requesting signatures optimistically, last 1 are [45TRrXn...]
2019-12-04 23:27:37,605 DEBUG [rx-extension-loader-39] c.w.s.appender.package$ - [01ce79bc 35.156.19.4:6868] Attempting to append extension [45TRrXn...]
2019-12-04 23:27:38,420 DEBUG [nio-worker-group-3-2] c.w.n.PeerDatabaseImpl - Suspending [df9e7bba 167.172.189.97:6868]
2019-12-04 23:27:38,421 DEBUG [rx-extension-loader-39] c.w.n.RxExtensionLoader$ - [01ce79bc 35.156.19.4:6868] Requesting signatures optimistically, last 1 are [45TRrXn...]
2019-12-04 23:27:41,427 DEBUG [rx-extension-loader-39] c.w.n.RxExtensionLoader$ - [01ce79bc 35.156.19.4:6868] Requesting signatures optimistically, last 1 are [45TRrXn...]
2019-12-04 23:27:42,634 DEBUG [rx-extension-loader-39] c.w.n.RxExtensionLoader$ - [01ce79bc 35.156.19.4:6868] Requesting signatures optimistically, last 1 are [45TRrXn...]
2019-12-04 23:27:42,838 DEBUG [nio-worker-group-3-3] c.w.network.NetworkServer$ - [d2bca6b9] connection timed out: /217.21.54.237:6868, outgoing channel count: 38
2019-12-04 23:27:42,838 DEBUG [rx-extension-loader-39] c.w.n.RxExtensionLoader$ - [01ce79bc 35.156.19.4:6868] Requesting signatures optimistically, last 1 are [45TRrXn...]
2019-12-04 23:27:43,673 DEBUG [nio-worker-group-3-7] c.w.n.PeerDatabaseImpl - Suspending [d0963cc9 167.99.42.44:6868]
2019-12-04 23:27:43,673 DEBUG [rx-extension-loader-39] c.w.n.RxExtensionLoader$ - [01ce79bc 35.156.19.4:6868] Requesting signatures optimistically, last 1 are [45TRrXn...]
2019-12-04 23:27:44,426 DEBUG [rx-extension-loader-39] c.w.n.RxExtensionLoader$ - [01ce79bc 35.156.19.4:6868] Requesting signatures optimistically, last 1 are [45TRrXn...]
2019-12-04 23:27:47,426 DEBUG [rx-extension-loader-39] c.w.n.RxExtensionLoader$ - [01ce79bc 35.156.19.4:6868] Requesting signatures optimistically, last 1 are [45TRrXn...]
2019-12-04 23:27:49,034 DEBUG [nio-worker-group-3-3] c.w.n.PeerDatabaseImpl - Suspending [c08f0e95 52.236.155.87:6868]
2019-12-04 23:27:51,223 INFO  [appender-44] c.w.s.BlockchainUpdaterImpl - New height: 1824851
2019-12-04 23:27:51,225 DEBUG [ion-context-global-855423] c.w.s.a.BlockAppender$ - [01ce79bc 35.156.19.4:6868] Appended Block(2DbMUv2W5XmvcPSjqmN6n1x4Kmqx9SxvNusVKSUZDBqtGq765Q3cLWSVGA5TEBmwydJVRwYUPenRXveBi3qV6qDB -> 5uSC9EG..., txs=0, features=Set())
2019-12-04 23:27:51,228 INFO  [appender-44] c.w.s.BlockchainUpdaterImpl - Removing blocks after 5uSC9EG... from blockchain
2019-12-04 23:27:51,228 DEBUG [appender-44] c.w.database.LevelDBWriter - Rolling back to block 5uSC9EGNWMZ6mrAgDtxhLC6Qf4pHtSHdCHUz6pG7A2M7eU3Q3FfPPNGxt7f1RvSwFoC7vbZyinF1F3V6PEbReeY7 at 1824850
2019-12-04 23:27:51,228 DEBUG [appender-44] c.w.database.LevelDBWriter - Rollback to block 5uSC9EGNWMZ6mrAgDtxhLC6Qf4pHtSHdCHUz6pG7A2M7eU3Q3FfPPNGxt7f1RvSwFoC7vbZyinF1F3V6PEbReeY7 at 1824850 completed
2019-12-04 23:27:51,230 DEBUG [rx-score-observer-38] c.w.n.RxScoreObserver$ - New local score: 403567078316540721004676, old: 403566798820418392072076, Δ279496122328932600
2019-12-04 23:27:51,236 DEBUG [rx-score-observer-38] c.w.n.RxScoreObserver$ - New local score: 403566798820418392072076, old: 403567078316540721004676, Δ-279496122328932600
2019-12-04 23:27:51,236 DEBUG [rx-extension-loader-39] c.w.n.RxExtensionLoader$ - [08998777 178.128.209.174:56848] Requesting signatures optimistically, last 1 are [45TRrXn...]
2019-12-04 23:27:51,520 INFO  [appender-44] c.w.s.BlockchainUpdaterImpl - New height: 1824851
2019-12-04 23:27:51,520 DEBUG [rx-extension-loader-39] c.w.s.appender.package$ - [01ce79bc 35.156.19.4:6868] Successfully appended extension [45TRrXn...]
2019-12-04 23:27:51,520 DEBUG [rx-score-observer-38] c.w.n.RxScoreObserver$ - New local score: 403567078316540721004676, old: 403566798820418392072076, Δ279496122328932600
2019-12-04 23:27:51,531 DEBUG [rx-extension-loader-39] c.w.mining.MinerImpl - Next attempt for acc=3PNEqDkLfEXoDqTCy1KwXNRVbxsSuDNUWfz in 445.122
2019-12-04 23:27:51,535 DEBUG [ion-context-global-676382] c.w.s.a.MicroblockAppender$ - [7d3b0f09 217.19.24.162:33422] Could not append microblock 45TRrXnG81zfHVnYqW9PPa9LCSPrBwiw9qQyJNTgQJbMYWW4y1EMYWpoKBk9AtG5SfuPu2HZkLEcX4pRDY7WxzKB: MicroBlockAppendError(It's first micro and it doesn't reference base block(which exists), 45TRrXnG81zfHVnYqW9PPa9LCSPrBwiw9qQyJNTgQJbMYWW4y1EMYWpoKBk9AtG5SfuPu2HZkLEcX4pRDY7WxzKB ~> 2DbMUv2...])
2019-12-04 23:27:51,677 INFO  [appender-44] c.w.s.BlockchainUpdaterImpl - MicroBlock(4B8KjxS... -> 45TRrXn..., txs=3) appended
2019-12-04 23:27:51,732 ERROR [ion-context-global-676382] c.w.Application - Error in Appender
java.lang.IllegalArgumentException: Invalid block ref: 2DbMUv2W5XmvcPSjqmN6n1x4Kmqx9SxvNusVKSUZDBqtGq765Q3cLWSVGA5TEBmwydJVRwYUPenRXveBi3qV6qDB
        at com.wavesplatform.consensus.GeneratingBalanceProvider$.$anonfun$balance$1(GeneratingBalanceProvider.scala:31)
        at com.wavesplatform.consensus.GeneratingBalanceProvider$.balance(GeneratingBalanceProvider.scala:31)
        at com.wavesplatform.state.package$BlockchainExt$.generatingBalance$extension(package.scala:197)
        at com.wavesplatform.mining.MinerImpl.nextBlockGenerationTime(Miner.scala:187)
        at com.wavesplatform.mining.MinerImpl.$anonfun$nextBlockGenOffsetWithConditions$2(Miner.scala:210)
        at com.wavesplatform.mining.MinerImpl.$anonfun$nextBlockGenOffsetWithConditions$1(Miner.scala:209)
        at com.wavesplatform.mining.MinerImpl.nextBlockGenOffsetWithConditions(Miner.scala:208)
        at com.wavesplatform.mining.MinerImpl.generateBlockTask(Miner.scala:220)
        at com.wavesplatform.mining.MinerImpl.$anonfun$scheduleMining$2(Miner.scala:258)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at com.wavesplatform.mining.MinerImpl.scheduleMining(Miner.scala:258)
        at com.wavesplatform.state.appender.BlockAppender$.$anonfun$apply$7(BlockAppender.scala:62)
        at com.wavesplatform.state.appender.BlockAppender$.$anonfun$apply$7$adapted(BlockAppender.scala:55)
        at monix.eval.Task$Map.apply(Task.scala:4514)
        at monix.eval.Task$Map.apply(Task.scala:4510)
        at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:170)
        at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:101)
        at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:74)
        at monix.eval.internal.TaskExecuteOn$AsyncRegister$$anon$1.run(TaskExecuteOn.scala:71)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2019-12-04 23:27:51,775 DEBUG [shutdownHook4] c.w.Application - Shutting down HistoryReplier
2019-12-04 23:27:51,813 INFO  [shutdownHook4] c.w.Application - HistoryReplier was shutdown successfully
2019-12-04 23:27:51,813 INFO  [appender-44] c.w.s.BlockchainUpdaterImpl - MicroBlock(25su7P5... -> 4B8KjxS..., txs=3) appended
2019-12-04 23:27:51,815 INFO  [shutdownHook4] c.w.Application - Closing REST API
2019-12-04 23:27:51,818 DEBUG [shutdownHook4] c.w.Application - Closing peer database
2019-12-04 23:27:51,821 INFO  [shutdownHook4] c.w.n.PeerDatabaseImpl - Saving 222 known peer(s) to peers.dat
2019-12-04 23:27:51,827 DEBUG [shutdownHook3] c.w.u.SystemInformationReporter$ - Available processors: 4
Max memory available: 2147483648
os.name: Linux
os.version: 4.15.0-70-generic
os.arch: amd64
java.version: 1.8.0_222
java.vendor: Private Build
java.home: /usr/lib/jvm/java-8-openjdk-amd64/jre
.....
Configuration: {"metrics":{"enable":"no","node-id":-1},"waves":{"blockchain":{"type":"MAINNET"},"config":{"directory":"/etc/waves"},"db":{"directory":"/var/lib/waves/data","max-cache-size":100000,"max-rollback-depth":2000,"remember-blocks":"3h","store-invoke-script-results":true,"store-transactions-by-address":true},"defaults":{"config":{"directory":"/etc/waves"},"directory":"/var/lib/waves"},
"directory":"/var/lib/waves","extensions":[],"extensions-shutdown-timeout":"5 minutes","features":{"auto-shutdown-on-unsupported-feature":"yes","supported":[14]},"miner":{"enable":"yes","interval-after-last-block-then-generation-is-allowed":"1d","max-pack-time":"5s","max-transactions-in-key-block":0,"max-transactions-in-micro-block":255,"micro-block-interval":"5s","min-micro-block-age":"5s","minimal-block-generation-offset":"1001ms","no-quorum-mining-delay":"5s","quorum":8},"network":{"bind-address":"0.0.0.0","black-list-residence-time":"15m","break-idle-connections-timeout":"5m","connection-timeout":"30s","declared-address":"5.189.148.174:6868","enable-blacklisting":"yes","enable-peers-exchange":"yes","file":"/var/lib/waves/peers.dat","handshake-timeout":"30s","known-peers":["13.228.86.201:6868","13.229.0.149:6868","18.195.170.147:6868","34.253.153.4:6868","35.156.19.4:6868","52.50.69.247:6868","52.52.46.76:6868","52.57.147.71:6868","52.214.55.18:6868","54.176.190.226:6868"]
,"max-inbound-connections":64,"max-outbound-connections":64,"max-single-host-connections":3,"max-unverified-peers":100,"node-name":"brox node","peers-broadcast-interval":"2m","peers-data-residence-time":"1d","port":6868,"received-txs-cache-timeout":"3m","suspension-residence-time":"1m","traffic-logger":{"ignore-rx-messages":[25],"ignore-tx-messages":[23,25]},"upnp":{"discover-timeout":"3s","enable":"no","gateway-timeout":"7s"}},"ntp-server":"pool.ntp.org","rest-api":{"api-key-different-host":"no","bind-address":"127.0.0.1","cors":"yes","distribution-address-limit":1000,"enable":"no","port":6869,"transactions-by-address-limit":10000},"rewards":{},"synchronization":{"history-replier":{"max-block-cache-size":20,"max-micro-block-cache-size":50},"invalid-blocks-storage":{"max-size":30000,"timeout":"5m"},"max-chain-length":101,"max-rollback":100,"micro-block-synchronizer":{"inv-cache-timeout":"45s","processed-micro-blocks-cache-timeout":"3m","wait-response-timeout":"2s"},"score-ttl":"90s","synchronization-timeout":"60s","utx-synchronizer":{"allow-tx-rebroadcasting":"yes","max-queue-size":5000,"max-threads":8,"network-tx-cache-size":1000000}},"utx":{"allow-blacklisted-transfer-to":[],"allow-skip-checks":true,"allow-transactions-from-smart-accounts":true,"blacklist-sender-addresses":[],"max-bytes-size":52428800,"max-scripted-size":5000,"max-size":100000}}}
2019-12-04 23:27:52,105 DEBUG [shutdownHook4] c.w.Application - Node's actor system shutdown successful
2019-12-04 23:27:52,113 INFO  [shutdownHook4] c.w.Application - Stopping network services
2019-12-04 23:27:52,117 DEBUG [shutdownHook4] c.w.network.NetworkServer$ - Unbound server
2019-12-04 23:27:52,140 DEBUG [shutdownHook4] c.w.network.NetworkServer$ - Closed all channels
2019-12-04 23:27:56,572 DEBUG [shutdownHook4] c.w.Application - Shutting down Miner
2019-12-04 23:27:56,572 DEBUG [shutdownHook4] c.w.Application - Shutting down MicroblockSynchronizer
2019-12-04 23:27:56,572 DEBUG [shutdownHook4] c.w.Application - Shutting down ScoreObserver
2019-12-04 23:27:56,579 DEBUG [shutdownHook4] c.w.Application - Shutting down ExtensionLoader
2019-12-04 23:27:56,580 DEBUG [shutdownHook4] c.w.Application - Shutting down Appender
2019-12-04 23:27:56,590 INFO  [shutdownHook4] c.w.Application - Appender was shutdown successfully
2019-12-04 23:27:56,591 INFO  [shutdownHook4] c.w.Application - Closing storage
2019-12-04 23:27:56,686 INFO  [shutdownHook4] c.wavesplatform.utils.NTP - Shutting down Time
2019-12-04 23:27:56,687 INFO  [shutdownHook4] c.w.Application - Shutdown complete
waves.service: Main process exited, code=exited, status=74/n/a
waves.service: Failed with result 'exit-code'.
```

**Comment by phearnot** [comment]
Fixed in #2805
