### ISSUE TITLE
Array too small

### ISSUE THREAD

**Issue by jansenmarc** [wavesplatform/Waves#29]
From time to time, i find errors as the following in my logs:

java.lang.IllegalArgumentException: array too small: 0 < 4
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
        at com.google.common.primitives.Ints.fromByteArray(Ints.java:321)
        at scorex.network.Handshake$$anonfun$parseBytes$1.apply(Handshake.scala:72)
        at scorex.network.Handshake$$anonfun$parseBytes$1.apply(Handshake.scala:43)
        at scala.util.Try$.apply(Try.scala:192)
        at scorex.network.Handshake$.parseBytes(Handshake.scala:43)
        at scorex.network.PeerConnectionHandler$$anonfun$handshake$1.applyOrElse(PeerConnectionHandler.scala:86)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at scorex.network.PeerConnectionHandler.aroundReceive(PeerConnectionHandler.scala:31)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)

The server seems to be working properly, even after these errors, but i think it should be checked anyway.

**Comment by asolovyov** [comment]
Usually it happens when the waves node tries to connect to a non-waves port, e.g. HTTP one. These attempts are caused by presence of the de facto invalid information about peers in the peers.dat and/or in the configuration file.

For now waves port used by majority of the testnet nodes is *6863*. 

Hence, this is not an issue. 

In the upcoming release, notification (in the logs) about such situations will be less aggressive.
