### ISSUE TITLE
V1.1.8 Doesn't seem to work with old dex versions

### ISSUE THREAD

**Issue by BlackTurtle123** [wavesplatform/Waves#2933]
**Describe the bug**
Version 1.1.8 doesn't seem to work with old dex versions due to the fact swagger is refactored.

**To Reproduce**
Install he latest deb release. Install the latest dex release (which is actually only compatible with v1.1.7)
Remove dex funtionality from the config => node starts fine

**Expected behavior**
Node should start dex should work.

**Screenshots**
```
java.lang.NoClassDefFoundError: com/github/swagger/akka/SwaggerHttpService
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.wavesplatform.dex.api.http.CompositeHttpService.<init>(CompositeHttpService.scala:20)
        at com.wavesplatform.dex.Matcher.start(Matcher.scala:323)
        at com.wavesplatform.Application.$anonfun$run$34(Application.scala:340)
        at com.wavesplatform.Application.$anonfun$run$34$adapted(Application.scala:340)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at com.wavesplatform.Application.run(Application.scala:340)
        at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:499)
        at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:480)
        at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
        at com.wavesplatform.Application$.startNode(Application.scala:480)
        at com.wavesplatform.Application$.main(Application.scala:463)
        at com.wavesplatform.Application.main(Application.scala)
Caused by: java.lang.ClassNotFoundException: com.github.swagger.akka.SwaggerHttpService
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 29 common frames omitted

```

**Desktop (please complete the following information):**
OS: [e.g. Debian/Ubuntu/iOS]

**Additional context**
I think building a new dex compatible with version 1.1.8 should do the job?

**Comment by vsuharnikov** [comment]
We haven't released DEX for new NODE version yet. Soon DEX 2.0.0 with NODE v1.1.7 will be released (it is in testing now) and then we will move to NODE v1.1.8.
