### ISSUE TITLE
Error validating transaction

### ISSUE THREAD

**Issue by wenderccc** [wavesplatform/Waves#2973]
My node is updating blockchain now. But after i restarted it, it started showing this strange errors.
```
Mar 06 14:52:57 wavsnode waves[3858]: WARN  c.w.n.UtxPoolSynchronizerImpl - Error validating transaction CrjACc91wSYqzfbb2T84fsW2Gka4ZpKN5Pv98gQpzSLq
Mar 06 14:52:57 wavsnode waves[3858]: java.util.concurrent.ExecutionException: Boxed InterruptedException
Mar 06 14:52:57 wavsnode waves[3858]:         at scala.concurrent.impl.Promise$.resolver(Promise.scala:86)
Mar 06 14:52:57 wavsnode waves[3858]:         at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:79)
Mar 06 14:52:57 wavsnode waves[3858]:         at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
Mar 06 14:52:57 wavsnode waves[3858]:         at scala.concurrent.Promise.complete(Promise.scala:53)
Mar 06 14:52:57 wavsnode waves[3858]:         at scala.concurrent.Promise.complete$(Promise.scala:52)
Mar 06 14:52:57 wavsnode waves[3858]:         at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
Mar 06 14:52:57 wavsnode waves[3858]:         at scala.concurrent.Promise.failure(Promise.scala:104)
Mar 06 14:52:57 wavsnode waves[3858]:         at scala.concurrent.Promise.failure$(Promise.scala:104)
Mar 06 14:52:57 wavsnode waves[3858]:         at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:187)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.utils.Schedulers$.$anonfun$executeCatchingInterruptedException$1(Schedulers.scala:139)
Mar 06 14:52:57 wavsnode waves[3858]:         at monix.execution.internal.InterceptRunnable.run(InterceptRunnable.scala:27)
Mar 06 14:52:57 wavsnode waves[3858]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Mar 06 14:52:57 wavsnode waves[3858]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Mar 06 14:52:57 wavsnode waves[3858]:         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.utils.Schedulers$TimedWrapper.run(Schedulers.scala:96)
Mar 06 14:52:57 wavsnode waves[3858]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Mar 06 14:52:57 wavsnode waves[3858]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Mar 06 14:52:57 wavsnode waves[3858]:         at java.base/java.lang.Thread.run(Thread.java:834)
Mar 06 14:52:57 wavsnode waves[3858]: Caused by: java.lang.InterruptedException: null
Mar 06 14:52:57 wavsnode waves[3858]:         at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1040)
Mar 06 14:52:57 wavsnode waves[3858]:         at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
Mar 06 14:52:57 wavsnode waves[3858]:         at java.base/java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lockInterruptibly(ReentrantReadWriteLock.java:783)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.state.BlockchainUpdaterImpl.accountData(BlockchainUpdaterImpl.scala:47)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.transaction.smart.WavesEnvironment.$anonfun$data$2(WavesEnvironment.scala:56)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.transaction.smart.WavesEnvironment.data(WavesEnvironment.scala:44)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.transaction.smart.WavesEnvironment.data(WavesEnvironment.scala:22)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.lang.v1.evaluator.ctx.impl.EnvironmentFunctions.$anonfun$getData$7(EnvironmentFunctions.scala:34)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.lang.v1.evaluator.ctx.impl.EnvironmentFunctions.getData(EnvironmentFunctions.scala:34)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.lang.v1.evaluator.ctx.impl.waves.Functions$$anon$1.apply(Functions.scala:39)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.lang.v1.evaluator.ctx.NativeFunction.eval(NativeFunction.scala:43)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.lang.v1.evaluator.EvaluatorV1.$anonfun$evalFunctionCall$9(EvaluatorV1.scala:100)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.lang.v1.task.TaskMT.$anonfun$flatMap$2(TaskMT.scala:38)
Mar 06 14:52:57 wavsnode waves[3858]:         at cats.Eval$.loop$1(Eval.scala:363)
Mar 06 14:52:57 wavsnode waves[3858]:         at cats.Eval$.cats$Eval$$evaluate(Eval.scala:368)
Mar 06 14:52:57 wavsnode waves[3858]:         at cats.Eval$FlatMap.value(Eval.scala:307)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.lang.v1.evaluator.EvaluatorV1.evalWithLogging(EvaluatorV1.scala:159)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.lang.v1.evaluator.ContractEvaluator$.apply(ContractEvaluator.scala:90)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.state.diffs.InvokeScriptTransactionDiff$.$anonfun$apply$10(InvokeScriptTransactionDiff.scala:91)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.state.diffs.InvokeScriptTransactionDiff$.$anonfun$apply$8(InvokeScriptTransactionDiff.scala:79)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.state.diffs.InvokeScriptTransactionDiff$.$anonfun$apply$2(InvokeScriptTransactionDiff.scala:78)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.state.diffs.InvokeScriptTransactionDiff$.apply(InvokeScriptTransactionDiff.scala:57)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.state.diffs.TransactionDiffer$.$anonfun$unverified$1(TransactionDiffer.scala:73)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.state.diffs.TransactionDiffer$.unverified(TransactionDiffer.scala:69)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.state.diffs.TransactionDiffer$.$anonfun$verified$9(TransactionDiffer.scala:56)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.state.diffs.TransactionDiffer$.$anonfun$verified$1(TransactionDiffer.scala:43)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.state.diffs.TransactionDiffer$.verified(TransactionDiffer.scala:42)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.state.diffs.TransactionDiffer$.$anonfun$apply$1(TransactionDiffer.scala:32)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.state.diffs.TransactionDiffer$.apply(TransactionDiffer.scala:34)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.utx.UtxPoolImpl.addTransaction(UtxPoolImpl.scala:187)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.utx.UtxPoolImpl.$anonfun$putNewTx$13(UtxPoolImpl.scala:156)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.utx.UtxPoolImpl.putNewTx(UtxPoolImpl.scala:156)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.utx.UtxPoolImpl.putIfNew(UtxPoolImpl.scala:65)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.network.UtxPoolSynchronizer$.$anonfun$apply$1(UtxPoolSynchronizer.scala:105)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.network.UtxPoolSynchronizerImpl.$anonfun$validateFuture$1(UtxPoolSynchronizer.scala:82)
Mar 06 14:52:57 wavsnode waves[3858]:         at com.wavesplatform.utils.Schedulers$.$anonfun$executeCatchingInterruptedException$1(Schedulers.scala:138)
Mar 06 14:52:57 wavsnode waves[3858]:         ... 8 common frames omitted
Mar 06 14:52:57 wavsnode waves[3858]: INFO  c.w.s.BlockchainUpdaterImpl - New height: 1959137
Mar 06 14:52:58 wavsnode waves[3858]: INFO  c.w.s.BlockchainUpdaterImpl - New height: 1959138
Mar 06 14:52:59 wavsnode waves[3858]: INFO  c.w.s.BlockchainUpdaterImpl - New height: 1959139
Mar 06 14:53:03 wavsnode waves[3858]: INFO  c.w.s.BlockchainUpdaterImpl - New height: 1959140
```
My node seems to run pretty well though.

**Comment by wenderccc** [comment]
Also this error appears only when i connect to VM from my pc.

**Comment by phearnot** [comment]
According to the logs, your node is actively downloading new blocks from the network (most likely the node was shut down for some time). While new blocks are continuously being applied, transactions are waiting for state lock. If this lock can not be acquired within predefined interval, transaction validation process is interrupted. A workaround is to wait for your node to completely synchronise with the network before broadcasting transactions.
