### ISSUE TITLE
Very very slow sync + error

### ISSUE THREAD

**Issue by Arkhh** [wavesplatform/Waves#30]
Hi,

 the sync is suspiciously slow ( 12h for 100 blocks ) and I keep on getting this error :

java.lang.IllegalStateException: Chunk 102703 no longer exists [1.4.192/9]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)
	at org.h2.mvstore.MVStore.getChunkIfFound(MVStore.java:951)
	at org.h2.mvstore.MVStore.getChunk(MVStore.java:933)
	at org.h2.mvstore.MVStore.removePage(MVStore.java:1981)
	at org.h2.mvstore.MVMap.removePage(MVMap.java:1097)
	at org.h2.mvstore.Page.removePage(Page.java:935)
	at org.h2.mvstore.Page.copy(Page.java:307)
	at org.h2.mvstore.MVMap.put(MVMap.java:119)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

I'm connected to 10+ peers and my current height is 100732

Thanks

**Comment by Arkhh** [comment]
installed v0.2.3 , cleared peers.dat , deleted the wallet folder & blockchain. Now it synced up and is working fine.
