### ISSUE TITLE
Постоянные падения базы

### ISSUE THREAD

**Issue by axxxxx** [wavesplatform/Waves#3269]
Постоянно падает база с ошибкой. После полной синхронизации работает от 5 минут до суток. Ошибка появилась после перехода с версии 1.1.9

`2020-09-11 19:42:14,403 INFO  [main] c.w.database.BloomFilter$ - Populating bloom filter for orders, this can take a while.
2020-09-11 19:43:50,205 INFO  [main] c.w.Application$ - Starting...
2020-09-11 19:43:50,215 INFO  [main] c.wavesplatform.utils.NTP - Initializing time
2020-09-11 19:43:50,798 INFO  [ctor.default-dispatcher-5] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2020-09-11 19:43:51,183 INFO  [main] c.w.Application$ - Waves v1.2.12 Blockchain Id: W
2020-09-11 19:43:51,198 DEBUG [main] c.w.database.package$ - Open DB at /var/lib/waves/data
2020-09-11 19:43:51,231 INFO  [main] c.w.d.LevelDBFactory$ - Loaded com.wavesplatform.database.jna.LevelDBJNADBFactory with com.wavesplatform.database.jna.LevelDBJNADBFactory@251f7d26
2020-09-11 19:43:55,948 INFO  [main] c.w.n.PeerDatabaseImpl - Loaded 151 known peer(s) from peers.dat
2020-09-11 19:43:56,042 DEBUG [main] c.w.database.BloomFilter$ - Loading bloom filter from /var/lib/waves/data/orders.bf
2020-09-11 19:43:57,710 DEBUG [main] c.w.database.BloomFilter$ - Could not load bloom filter from /var/lib/waves/data/orders.bf
java.lang.IllegalArgumentException: requirement failed: filter is stale
	at com.wavesplatform.database.BloomFilter$.$anonfun$tryLoad$1(BloomFilter.scala:74)
	at com.wavesplatform.database.BloomFilter$.tryLoad(BloomFilter.scala:62)
	at com.wavesplatform.database.BloomFilter$.loadOrPopulate(BloomFilter.scala:96)
	at com.wavesplatform.database.LevelDBWriter$.load$1(LevelDBWriter.scala:116)
	at com.wavesplatform.database.LevelDBWriter$.apply(LevelDBWriter.scala:118)
	at com.wavesplatform.history.StorageFactory$.apply(StorageFactory.scala:26)
	at com.wavesplatform.Application.<init>(Application.scala:113)
	at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:572)
	at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:569)
	at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
	at com.wavesplatform.Application$.startNode(Application.scala:569)
	at com.wavesplatform.Application$.main(Application.scala:538)
	at com.wavesplatform.Application.main(Application.scala)
`
В чем причина?

**Comment by msmolyakov** [comment]
> Ошибка появилась после перехода с версии 1.1.9

Какую именно версию теперь используете? Какие характеристики вашего сервера?

Обновитесь на последнюю версию 1.2.12. В ней решены проблемы с производительностью, из-за которых в определенных случаях нода могла прерывать работу.

Также, по части лога ниже, процесс ноды завершается принудительно. Нода перестраивала блум фильтры, но потом без каких-либо сообщений об остановке появилось сообщение сразу о запуске ноды:
```
2020-09-11 19:42:14,403 INFO [main] c.w.database.BloomFilter$ - Populating bloom filter for orders, this can take a while. 2020-09-11 19:43:50,205 INFO [main] c.w.Application$ - Starting...
```
При такой остановке нода не успевает сохранить текущие блум фильтры на диск. При запуске нода понимает, что фильтры повреждены, поэтому начинает заново их перестраивать. Для мейннета это может занимать около получаса, и в течение этого времени нода не подлючается к блокчейну и не отвечает на запросы.

Поэтому важно корректно останавливать ноду. Послать ей shutdown сигнал и дать сохранить фильтры на диск.

Сейчас мы исследуем, как сделать этот процесс более надежным.

**Comment by axxxxx** [comment]
С 1.1.9 обновился сразу до 1.2.12, на ней стал получать эти ошибки, попробовал 1.2.10, это же самое. Вернул обратно 1.2.12. 
Сервер: Debian 9.2 (x86_64), 4гб память, 8гб из 78гб свободно на диске (с учетом синхронизированной базы)

`Также, по части лога ниже, процесс ноды завершается принудительно. Нода перестраивала блум фильтры, но потом без каких-либо сообщений об остановке появилось сообщение сразу о запуске ноды:`

Лог не обнулял после падения, сразу проводил новые "эксперименты", видимо по этому он не совсем корректно выглядит. Суть в следующем - после запуска проходит время (от 5 минут до 1 суток), нода пропадает из процессов на сервере и не отвечает на команды (выключилась). Сколько бы потом времени не проходило, она не оживет. После последнего падения и завершения "экспериментов" прошло уже несколько дней. 

Запущу сейчас ноду, как упадет - выложу полный лог.

**Comment by axxxxx** [comment]
Идут 3-и сутки "работы" ноды. Она как обычно отработала какое-то время (не долго). Далее "упала", никаких признаков жизни не подает, только в логи постоянно пишет следующее (взят произвольный кусок лога с конца файла):

`2020-09-21 11:26:01,443 INFO  [ctor.default-dispatcher-6] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2020-09-21 11:26:01,871 INFO  [main] c.w.Application$ - Waves v1.2.12 Blockchain Id: W
2020-09-21 11:26:01,884 DEBUG [main] c.w.database.package$ - Open DB at /var/lib/waves/data
2020-09-21 11:26:01,923 INFO  [main] c.w.d.LevelDBFactory$ - Loaded com.wavesplatform.database.jna.LevelDBJNADBFactory with com.wavesplatform.database.jna.LevelDBJNADBFactory@36ac8a63
2020-09-21 11:26:06,779 INFO  [main] c.w.n.PeerDatabaseImpl - Loaded 152 known peer(s) from peers.dat
2020-09-21 11:26:06,906 DEBUG [main] c.w.database.BloomFilter$ - Loading bloom filter from /var/lib/waves/data/orders.bf
2020-09-21 11:26:08,503 DEBUG [main] c.w.database.BloomFilter$ - Could not load bloom filter from /var/lib/waves/data/orders.bf
java.lang.IllegalArgumentException: requirement failed: filter is stale
	at com.wavesplatform.database.BloomFilter$.$anonfun$tryLoad$1(BloomFilter.scala:74)
	at com.wavesplatform.database.BloomFilter$.tryLoad(BloomFilter.scala:62)
	at com.wavesplatform.database.BloomFilter$.loadOrPopulate(BloomFilter.scala:96)
	at com.wavesplatform.database.LevelDBWriter$.load$1(LevelDBWriter.scala:116)
	at com.wavesplatform.database.LevelDBWriter$.apply(LevelDBWriter.scala:118)
	at com.wavesplatform.history.StorageFactory$.apply(StorageFactory.scala:26)
	at com.wavesplatform.Application.<init>(Application.scala:113)
	at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:572)
	at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:569)
	at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
	at com.wavesplatform.Application$.startNode(Application.scala:569)
	at com.wavesplatform.Application$.main(Application.scala:538)
	at com.wavesplatform.Application.main(Application.scala)
2020-09-21 11:26:08,506 INFO  [main] c.w.database.BloomFilter$ - Populating bloom filter for orders, this can take a while.
2020-09-21 11:27:26,384 INFO  [main] c.w.Application$ - Starting...
2020-09-21 11:27:26,392 INFO  [main] c.wavesplatform.utils.NTP - Initializing time
2020-09-21 11:27:26,908 INFO  [ctor.default-dispatcher-5] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2020-09-21 11:27:27,267 INFO  [main] c.w.Application$ - Waves v1.2.12 Blockchain Id: W
2020-09-21 11:27:27,293 DEBUG [main] c.w.database.package$ - Open DB at /var/lib/waves/data
2020-09-21 11:27:27,331 INFO  [main] c.w.d.LevelDBFactory$ - Loaded com.wavesplatform.database.jna.LevelDBJNADBFactory with com.wavesplatform.database.jna.LevelDBJNADBFactory@49a64d82
2020-09-21 11:27:32,465 INFO  [main] c.w.n.PeerDatabaseImpl - Loaded 152 known peer(s) from peers.dat
2020-09-21 11:27:32,574 DEBUG [main] c.w.database.BloomFilter$ - Loading bloom filter from /var/lib/waves/data/orders.bf
2020-09-21 11:27:34,511 DEBUG [main] c.w.database.BloomFilter$ - Could not load bloom filter from /var/lib/waves/data/orders.bf
java.lang.IllegalArgumentException: requirement failed: filter is stale
	at com.wavesplatform.database.BloomFilter$.$anonfun$tryLoad$1(BloomFilter.scala:74)
	at com.wavesplatform.database.BloomFilter$.tryLoad(BloomFilter.scala:62)
	at com.wavesplatform.database.BloomFilter$.loadOrPopulate(BloomFilter.scala:96)
	at com.wavesplatform.database.LevelDBWriter$.load$1(LevelDBWriter.scala:116)
	at com.wavesplatform.database.LevelDBWriter$.apply(LevelDBWriter.scala:118)
	at com.wavesplatform.history.StorageFactory$.apply(StorageFactory.scala:26)
	at com.wavesplatform.Application.<init>(Application.scala:113)
	at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:572)
	at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:569)
	at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
	at com.wavesplatform.Application$.startNode(Application.scala:569)
	at com.wavesplatform.Application$.main(Application.scala:538)
	at com.wavesplatform.Application.main(Application.scala)
2020-09-21 11:27:34,514 INFO  [main] c.w.database.BloomFilter$ - Populating bloom filter for orders, this can take a while.
2020-09-21 11:28:52,715 INFO  [main] c.w.Application$ - Starting...
2020-09-21 11:28:52,739 INFO  [main] c.wavesplatform.utils.NTP - Initializing time
2020-09-21 11:28:53,299 INFO  [ctor.default-dispatcher-5] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2020-09-21 11:28:53,659 INFO  [main] c.w.Application$ - Waves v1.2.12 Blockchain Id: W
2020-09-21 11:28:53,674 DEBUG [main] c.w.database.package$ - Open DB at /var/lib/waves/data
2020-09-21 11:28:53,708 INFO  [main] c.w.d.LevelDBFactory$ - Loaded com.wavesplatform.database.jna.LevelDBJNADBFactory with com.wavesplatform.database.jna.LevelDBJNADBFactory@251f7d26
2020-09-21 11:28:58,711 INFO  [main] c.w.n.PeerDatabaseImpl - Loaded 152 known peer(s) from peers.dat
2020-09-21 11:28:58,846 DEBUG [main] c.w.database.BloomFilter$ - Loading bloom filter from /var/lib/waves/data/orders.bf
2020-09-21 11:29:00,477 DEBUG [main] c.w.database.BloomFilter$ - Could not load bloom filter from /var/lib/waves/data/orders.bf
java.lang.IllegalArgumentException: requirement failed: filter is stale
	at com.wavesplatform.database.BloomFilter$.$anonfun$tryLoad$1(BloomFilter.scala:74)
	at com.wavesplatform.database.BloomFilter$.tryLoad(BloomFilter.scala:62)
	at com.wavesplatform.database.BloomFilter$.loadOrPopulate(BloomFilter.scala:96)
	at com.wavesplatform.database.LevelDBWriter$.load$1(LevelDBWriter.scala:116)
	at com.wavesplatform.database.LevelDBWriter$.apply(LevelDBWriter.scala:118)
	at com.wavesplatform.history.StorageFactory$.apply(StorageFactory.scala:26)
	at com.wavesplatform.Application.<init>(Application.scala:113)
	at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:572)
	at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:569)
	at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
	at com.wavesplatform.Application$.startNode(Application.scala:569)
	at com.wavesplatform.Application$.main(Application.scala:538)
	at com.wavesplatform.Application.main(Application.scala)
2020-09-21 11:29:00,480 INFO  [main] c.w.database.BloomFilter$ - Populating bloom filter for orders, this can take a while.
2020-09-21 11:30:16,227 INFO  [main] c.w.Application$ - Starting...
2020-09-21 11:30:16,236 INFO  [main] c.wavesplatform.utils.NTP - Initializing time
2020-09-21 11:30:16,784 INFO  [ctor.default-dispatcher-6] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2020-09-21 11:30:17,122 INFO  [main] c.w.Application$ - Waves v1.2.12 Blockchain Id: W
2020-09-21 11:30:17,134 DEBUG [main] c.w.database.package$ - Open DB at /var/lib/waves/data
2020-09-21 11:30:17,165 INFO  [main] c.w.d.LevelDBFactory$ - Loaded com.wavesplatform.database.jna.LevelDBJNADBFactory with com.wavesplatform.database.jna.LevelDBJNADBFactory@251f7d26
2020-09-21 11:30:21,788 INFO  [main] c.w.n.PeerDatabaseImpl - Loaded 152 known peer(s) from peers.dat
2020-09-21 11:30:21,886 DEBUG [main] c.w.database.BloomFilter$ - Loading bloom filter from /var/lib/waves/data/orders.bf
2020-09-21 11:30:23,471 DEBUG [main] c.w.database.BloomFilter$ - Could not load bloom filter from /var/lib/waves/data/orders.bf
java.lang.IllegalArgumentException: requirement failed: filter is stale
	at com.wavesplatform.database.BloomFilter$.$anonfun$tryLoad$1(BloomFilter.scala:74)
	at com.wavesplatform.database.BloomFilter$.tryLoad(BloomFilter.scala:62)
	at com.wavesplatform.database.BloomFilter$.loadOrPopulate(BloomFilter.scala:96)
	at com.wavesplatform.database.LevelDBWriter$.load$1(LevelDBWriter.scala:116)
	at com.wavesplatform.database.LevelDBWriter$.apply(LevelDBWriter.scala:118)
	at com.wavesplatform.history.StorageFactory$.apply(StorageFactory.scala:26)
	at com.wavesplatform.Application.<init>(Application.scala:113)
	at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:572)
	at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:569)
	at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
	at com.wavesplatform.Application$.startNode(Application.scala:569)
	at com.wavesplatform.Application$.main(Application.scala:538)
	at com.wavesplatform.Application.main(Application.scala)
2020-09-21 11:30:23,474 INFO  [main] c.w.database.BloomFilter$ - Populating bloom filter for orders, this can take a while.
2020-09-21 11:31:40,381 INFO  [main] c.w.Application$ - Starting...
2020-09-21 11:31:40,390 INFO  [main] c.wavesplatform.utils.NTP - Initializing time
2020-09-21 11:31:40,934 INFO  [ctor.default-dispatcher-6] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2020-09-21 11:31:41,276 INFO  [main] c.w.Application$ - Waves v1.2.12 Blockchain Id: W
2020-09-21 11:31:41,290 DEBUG [main] c.w.database.package$ - Open DB at /var/lib/waves/data
2020-09-21 11:31:41,326 INFO  [main] c.w.d.LevelDBFactory$ - Loaded com.wavesplatform.database.jna.LevelDBJNADBFactory with com.wavesplatform.database.jna.LevelDBJNADBFactory@36ac8a63
2020-09-21 11:31:46,032 INFO  [main] c.w.n.PeerDatabaseImpl - Loaded 152 known peer(s) from peers.dat
2020-09-21 11:31:46,148 DEBUG [main] c.w.database.BloomFilter$ - Loading bloom filter from /var/lib/waves/data/orders.bf
2020-09-21 11:31:47,859 DEBUG [main] c.w.database.BloomFilter$ - Could not load bloom filter from /var/lib/waves/data/orders.bf
java.lang.IllegalArgumentException: requirement failed: filter is stale
	at com.wavesplatform.database.BloomFilter$.$anonfun$tryLoad$1(BloomFilter.scala:74)
	at com.wavesplatform.database.BloomFilter$.tryLoad(BloomFilter.scala:62)
	at com.wavesplatform.database.BloomFilter$.loadOrPopulate(BloomFilter.scala:96)
	at com.wavesplatform.database.LevelDBWriter$.load$1(LevelDBWriter.scala:116)
	at com.wavesplatform.database.LevelDBWriter$.apply(LevelDBWriter.scala:118)
	at com.wavesplatform.history.StorageFactory$.apply(StorageFactory.scala:26)
	at com.wavesplatform.Application.<init>(Application.scala:113)
	at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:572)
	at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:569)
	at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
	at com.wavesplatform.Application$.startNode(Application.scala:569)
	at com.wavesplatform.Application$.main(Application.scala:538)
	at com.wavesplatform.Application.main(Application.scala)
2020-09-21 11:31:47,862 INFO  [main] c.w.database.BloomFilter$ - Populating bloom filter for orders, this can take a while.
2020-09-21 11:33:04,269 INFO  [main] c.w.Application$ - Starting...
2020-09-21 11:33:04,279 INFO  [main] c.wavesplatform.utils.NTP - Initializing time
2020-09-21 11:33:04,820 INFO  [ctor.default-dispatcher-5] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2020-09-21 11:33:05,195 INFO  [main] c.w.Application$ - Waves v1.2.12 Blockchain Id: W
2020-09-21 11:33:05,207 DEBUG [main] c.w.database.package$ - Open DB at /var/lib/waves/data
2020-09-21 11:33:05,242 INFO  [main] c.w.d.LevelDBFactory$ - Loaded com.wavesplatform.database.jna.LevelDBJNADBFactory with com.wavesplatform.database.jna.LevelDBJNADBFactory@251f7d26
2020-09-21 11:33:09,865 INFO  [main] c.w.n.PeerDatabaseImpl - Loaded 152 known peer(s) from peers.dat
2020-09-21 11:33:09,983 DEBUG [main] c.w.database.BloomFilter$ - Loading bloom filter from /var/lib/waves/data/orders.bf
2020-09-21 11:33:11,630 DEBUG [main] c.w.database.BloomFilter$ - Could not load bloom filter from /var/lib/waves/data/orders.bf
java.lang.IllegalArgumentException: requirement failed: filter is stale
	at com.wavesplatform.database.BloomFilter$.$anonfun$tryLoad$1(BloomFilter.scala:74)
	at com.wavesplatform.database.BloomFilter$.tryLoad(BloomFilter.scala:62)
	at com.wavesplatform.database.BloomFilter$.loadOrPopulate(BloomFilter.scala:96)
	at com.wavesplatform.database.LevelDBWriter$.load$1(LevelDBWriter.scala:116)
	at com.wavesplatform.database.LevelDBWriter$.apply(LevelDBWriter.scala:118)
	at com.wavesplatform.history.StorageFactory$.apply(StorageFactory.scala:26)
	at com.wavesplatform.Application.<init>(Application.scala:113)
	at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:572)
	at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:569)
	at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
	at com.wavesplatform.Application$.startNode(Application.scala:569)
	at com.wavesplatform.Application$.main(Application.scala:538)
	at com.wavesplatform.Application.main(Application.scala)
2020-09-21 11:33:11,632 INFO  [main] c.w.database.BloomFilter$ - Populating bloom filter for orders, this can take a while.
2020-09-21 11:34:27,808 INFO  [main] c.w.Application$ - Starting...
2020-09-21 11:34:27,818 INFO  [main] c.wavesplatform.utils.NTP - Initializing time
2020-09-21 11:34:28,340 INFO  [ctor.default-dispatcher-6] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2020-09-21 11:34:28,684 INFO  [main] c.w.Application$ - Waves v1.2.12 Blockchain Id: W
2020-09-21 11:34:28,697 DEBUG [main] c.w.database.package$ - Open DB at /var/lib/waves/data
2020-09-21 11:34:28,734 INFO  [main] c.w.d.LevelDBFactory$ - Loaded com.wavesplatform.database.jna.LevelDBJNADBFactory with com.wavesplatform.database.jna.LevelDBJNADBFactory@36ac8a63
2020-09-21 11:34:33,497 INFO  [main] c.w.n.PeerDatabaseImpl - Loaded 152 known peer(s) from peers.dat
2020-09-21 11:34:33,607 DEBUG [main] c.w.database.BloomFilter$ - Loading bloom filter from /var/lib/waves/data/orders.bf
2020-09-21 11:34:35,283 DEBUG [main] c.w.database.BloomFilter$ - Could not load bloom filter from /var/lib/waves/data/orders.bf
java.lang.IllegalArgumentException: requirement failed: filter is stale
	at com.wavesplatform.database.BloomFilter$.$anonfun$tryLoad$1(BloomFilter.scala:74)
	at com.wavesplatform.database.BloomFilter$.tryLoad(BloomFilter.scala:62)
	at com.wavesplatform.database.BloomFilter$.loadOrPopulate(BloomFilter.scala:96)
	at com.wavesplatform.database.LevelDBWriter$.load$1(LevelDBWriter.scala:116)
	at com.wavesplatform.database.LevelDBWriter$.apply(LevelDBWriter.scala:118)
	at com.wavesplatform.history.StorageFactory$.apply(StorageFactory.scala:26)
	at com.wavesplatform.Application.<init>(Application.scala:113)
	at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:572)
	at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:569)
	at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
	at com.wavesplatform.Application$.startNode(Application.scala:569)
	at com.wavesplatform.Application$.main(Application.scala:538)
	at com.wavesplatform.Application.main(Application.scala)
2020-09-21 11:34:35,288 INFO  [main] c.w.database.BloomFilter$ - Populating bloom filter for orders, this can take a while.
2020-09-21 11:35:52,116 INFO  [main] c.w.Application$ - Starting...
2020-09-21 11:35:52,129 INFO  [main] c.wavesplatform.utils.NTP - Initializing time
2020-09-21 11:35:52,682 INFO  [ctor.default-dispatcher-6] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2020-09-21 11:35:52,992 INFO  [main] c.w.Application$ - Waves v1.2.12 Blockchain Id: W
2020-09-21 11:35:53,004 DEBUG [main] c.w.database.package$ - Open DB at /var/lib/waves/data
2020-09-21 11:35:53,039 INFO  [main] c.w.d.LevelDBFactory$ - Loaded com.wavesplatform.database.jna.LevelDBJNADBFactory with com.wavesplatform.database.jna.LevelDBJNADBFactory@251f7d26
2020-09-21 11:35:57,890 INFO  [main] c.w.n.PeerDatabaseImpl - Loaded 152 known peer(s) from peers.dat
2020-09-21 11:35:58,032 DEBUG [main] c.w.database.BloomFilter$ - Loading bloom filter from /var/lib/waves/data/orders.bf
2020-09-21 11:35:59,881 DEBUG [main] c.w.database.BloomFilter$ - Could not load bloom filter from /var/lib/waves/data/orders.bf
java.lang.IllegalArgumentException: requirement failed: filter is stale
	at com.wavesplatform.database.BloomFilter$.$anonfun$tryLoad$1(BloomFilter.scala:74)
	at com.wavesplatform.database.BloomFilter$.tryLoad(BloomFilter.scala:62)
	at com.wavesplatform.database.BloomFilter$.loadOrPopulate(BloomFilter.scala:96)
	at com.wavesplatform.database.LevelDBWriter$.load$1(LevelDBWriter.scala:116)
	at com.wavesplatform.database.LevelDBWriter$.apply(LevelDBWriter.scala:118)
	at com.wavesplatform.history.StorageFactory$.apply(StorageFactory.scala:26)
	at com.wavesplatform.Application.<init>(Application.scala:113)
	at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:572)
	at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:569)
	at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
	at com.wavesplatform.Application$.startNode(Application.scala:569)
	at com.wavesplatform.Application$.main(Application.scala:538)
	at com.wavesplatform.Application.main(Application.scala)
2020-09-21 11:35:59,883 INFO  [main] c.w.database.BloomFilter$ - Populating bloom filter for orders, this can take a while.
2020-09-21 11:37:15,367 INFO  [main] c.w.Application$ - Starting...
2020-09-21 11:37:15,379 INFO  [main] c.wavesplatform.utils.NTP - Initializing time
2020-09-21 11:37:15,959 INFO  [ctor.default-dispatcher-6] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2020-09-21 11:37:16,366 INFO  [main] c.w.Application$ - Waves v1.2.12 Blockchain Id: W
2020-09-21 11:37:16,381 DEBUG [main] c.w.database.package$ - Open DB at /var/lib/waves/data
2020-09-21 11:37:16,427 INFO  [main] c.w.d.LevelDBFactory$ - Loaded com.wavesplatform.database.jna.LevelDBJNADBFactory with com.wavesplatform.database.jna.LevelDBJNADBFactory@3dddbe65
2020-09-21 11:37:21,223 INFO  [main] c.w.n.PeerDatabaseImpl - Loaded 152 known peer(s) from peers.dat
2020-09-21 11:37:21,322 DEBUG [main] c.w.database.BloomFilter$ - Loading bloom filter from /var/lib/waves/data/orders.bf
2020-09-21 11:37:22,913 DEBUG [main] c.w.database.BloomFilter$ - Could not load bloom filter from /var/lib/waves/data/orders.bf
java.lang.IllegalArgumentException: requirement failed: filter is stale
	at com.wavesplatform.database.BloomFilter$.$anonfun$tryLoad$1(BloomFilter.scala:74)
	at com.wavesplatform.database.BloomFilter$.tryLoad(BloomFilter.scala:62)
	at com.wavesplatform.database.BloomFilter$.loadOrPopulate(BloomFilter.scala:96)
	at com.wavesplatform.database.LevelDBWriter$.load$1(LevelDBWriter.scala:116)
	at com.wavesplatform.database.LevelDBWriter$.apply(LevelDBWriter.scala:118)
	at com.wavesplatform.history.StorageFactory$.apply(StorageFactory.scala:26)
	at com.wavesplatform.Application.<init>(Application.scala:113)
	at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:572)
	at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:569)
	at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
	at com.wavesplatform.Application$.startNode(Application.scala:569)
	at com.wavesplatform.Application$.main(Application.scala:538)
	at com.wavesplatform.Application.main(Application.scala)
2020-09-21 11:37:22,916 INFO  [main] c.w.database.BloomFilter$ - Populating bloom filter for orders, this can take a while.
2020-09-21 11:38:38,113 INFO  [main] c.w.Application$ - Starting...
2020-09-21 11:38:38,138 INFO  [main] c.wavesplatform.utils.NTP - Initializing time
2020-09-21 11:38:38,690 INFO  [ctor.default-dispatcher-6] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2020-09-21 11:38:39,031 INFO  [main] c.w.Application$ - Waves v1.2.12 Blockchain Id: W
2020-09-21 11:38:39,049 DEBUG [main] c.w.database.package$ - Open DB at /var/lib/waves/data
2020-09-21 11:38:39,083 INFO  [main] c.w.d.LevelDBFactory$ - Loaded com.wavesplatform.database.jna.LevelDBJNADBFactory with com.wavesplatform.database.jna.LevelDBJNADBFactory@52c8295b
2020-09-21 11:38:43,963 INFO  [main] c.w.n.PeerDatabaseImpl - Loaded 152 known peer(s) from peers.dat
2020-09-21 11:38:44,063 DEBUG [main] c.w.database.BloomFilter$ - Loading bloom filter from /var/lib/waves/data/orders.bf
2020-09-21 11:38:45,727 DEBUG [main] c.w.database.BloomFilter$ - Could not load bloom filter from /var/lib/waves/data/orders.bf
java.lang.IllegalArgumentException: requirement failed: filter is stale
	at com.wavesplatform.database.BloomFilter$.$anonfun$tryLoad$1(BloomFilter.scala:74)
	at com.wavesplatform.database.BloomFilter$.tryLoad(BloomFilter.scala:62)
	at com.wavesplatform.database.BloomFilter$.loadOrPopulate(BloomFilter.scala:96)
	at com.wavesplatform.database.LevelDBWriter$.load$1(LevelDBWriter.scala:116)
	at com.wavesplatform.database.LevelDBWriter$.apply(LevelDBWriter.scala:118)
	at com.wavesplatform.history.StorageFactory$.apply(StorageFactory.scala:26)
	at com.wavesplatform.Application.<init>(Application.scala:113)
	at com.wavesplatform.Application$.$anonfun$startNode$4(Application.scala:572)
	at com.wavesplatform.Application$.$anonfun$startNode$4$adapted(Application.scala:569)
	at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
	at com.wavesplatform.Application$.startNode(Application.scala:569)
	at com.wavesplatform.Application$.main(Application.scala:538)
	at com.wavesplatform.Application.main(Application.scala)
2020-09-21 11:38:45,729 INFO  [main] c.w.database.BloomFilter$ - Populating bloom filter for orders, this can take a while.
`

Объясните пожалуйста, что происходит с ней?

**Comment by msmolyakov** [comment]
> Лог не обнулял после падения, сразу проводил новые "эксперименты", видимо по этому он не совсем корректно выглядит

Лог и не нужно обнулять. При корректной остановке ноды были бы примерно такие сообщения:
```
systemd[1]: Stopping Waves node...
waves[29030]: INFO  c.w.Application - HistoryReplier was shutdown successfully
waves[29030]: INFO  c.w.Application - Closing REST API
waves[29030]: INFO  c.w.Application - Stopping network services
waves[29030]: INFO  c.w.d.BloomFilterImpl - Saving bloom filter to /var/lib/waves/data/orders.bf
waves[29030]: INFO  c.w.d.BloomFilterImpl - Saving bloom filter to /var/lib/waves/data/account-data.bf
waves[29030]: INFO  c.w.d.BloomFilterImpl - Saving bloom filter to /var/lib/waves/data/waves-balances.bf
waves[29030]: INFO  c.w.d.BloomFilterImpl - Saving bloom filter to /var/lib/waves/data/asset-balances.bf
waves[29030]: INFO  c.w.Application - Appender was shutdown successfully
waves[29030]: INFO  c.w.Application - Closing storage
waves[29030]: INFO  c.wavesplatform.utils.NTP - Shutting down Time
waves[29030]: INFO  c.w.Application - Shutdown complete
```
Но их нет. Значит нода завершает работу некорректно. Об этом же говорят ошибки о проблемах с bloom фильтрами:
```
2020-09-21 11:26:08,503 DEBUG [main] c.w.database.BloomFilter$ - Could not load bloom filter from /var/lib/waves/data/orders.bf
java.lang.IllegalArgumentException: requirement failed: filter is stale
2020-09-21 11:26:08,506 INFO [main] c.w.database.BloomFilter$ - Populating bloom filter for orders, this can take a while.
2020-09-21 11:27:26,384 INFO [main] c.w.Application$ - Starting...
```
Здесь она пытается перестроить bloom фильтр, но её работа некорректно прерывается и она пытается запуститься снова.

Какая версия Java используется?
Сколько свободного места на диске?
Сколько оперативной памяти на сервере? Сколько памяти свободно, когда нода выключена?
Какие настройки указаны в `/etc/waves/application.ini`? Конкретно интересуют параметры `-J-Xms` и `-J-Xmx`.

**Comment by axxxxx** [comment]
java :

> openjdk version "1.8.0_151"
> OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-1~deb9u1-b12)
> OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

Место :

> 5200 M / 78 GB (6%)

p.s.: после запуска на новой базе (sudo -u waves bash -c "wget -qO- http://blockchain.wavesnodes.com/blockchain_last.tar.gz --show-progress | tar xf -") места около 10%

Памяти на сервере 4гб

Памяти без ноды:

> KiB Mem :  4013020 total,  1936480 free,  1737856 used,   338684 buff/cache

Памяти с рабочей нодой (пока не упала):

> KiB Mem :  4013020 total,   132532 free,  2960980 used,   919508 buff/cache

Настройки:
> -J-Xms128m
> -J-Xmx2g

**Comment by msmolyakov** [comment]
Прошу прощения за долгий ответ. Проблема еще актуальна?

Если да, то я по приведенным значениям видно, что для ноды выделяется 2 Гб памяти, но до её запуска свободно меньше, ≈1.9. В таком случае при попытке забрать весь разрешенный объем памяти процесс может быть прерван с ошибкой OutOfMemory.

В этом можно убедиться по сообщениям в stdout в момент падения:

`journalctl -u waves -f`

**Comment by DrBlast** [comment]
Closed due to inactivity. Please feel free to reopen the issue if this problem is still actual.
