### ISSUE TITLE
Dockerfile instance not working : unable to access jar file

### ISSUE THREAD

**Issue by schwab** [wavesplatform/Waves#3284]
Attempting to run the simplest docker implementation (on Ubuntu 20.04 host) results in a jar file failure
 
**To Reproduce**
1. docker run -it wavesplatform/node

**Expected behavior**
Service should startup and meet all dependencies automatically. Instead we get a 404 when trying download some resource (expect that this file is missing or moved and Dockerfile needs an updated reference... /waves-node/waves-all-latest.jar)

**Screenshots**
![Screenshot from 2020-10-09 09-48-20](https://user-images.githubusercontent.com/1517342/95597747-a6dc2100-0a14-11eb-87da-ceec756e7041.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**
docker run -it wavesplatform/node
Latest version for TESTNET is:  Version 1.2.13 (Mainnet + Testnet + Stagenet)
Version: latest(1.2.13)
Traceback (most recent call last):
  File "/waves-node/starter.py", line 183, in <module>
    urllib.request.urlretrieve(url, file_path)
  File "/usr/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/waves-node/starter.py", line 186, in <module>
    urllib.request.urlretrieve(url, file_path)
  File "/usr/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Node is starting...
Error: Unable to access jarfile /waves-node/waves-all-latest.jar

**Comment by msmolyakov** [comment]
This image is deprecated. Please use this: https://hub.docker.com/r/wavesplatform/wavesnode

**Comment by schwab** [comment]
Thank you for the reference. I'll close this.

**Comment by msmolyakov** [comment]
Hi, @schwab!

It turned out that this image was broken. Now it has already been fixed with tags `1.2.13` and `latest`. If you have any problems using it, then pull it and try again, please.
https://hub.docker.com/r/wavesplatform/wavesnode
