### ISSUE TITLE
MessageToMessageEncoder.java:104

### ISSUE THREAD

**Issue by affiliatepayday** [wavesplatform/Waves#3462]
I am on a cloned chain oF 1.2.17. When trying to sync nodes the following error happens:

```
[ecution-context-global-54] kamon.metric.Timer - Failed to record value [-119000000] on 
[span.processing-time,{operation=block-appender,error=true}] because the value is outside 
of the configured range. The recorded value was adjusted to the highest trackable value
 [3600000000000]. You might need to change your dynamic range configuration for this metric

 DEBUG [rx-extension-loader-37] c.t.n.RxExtensionLoader$ - [c3226df0 first.public.ip:6864] 
 Requesting signatures, last 94 are (total=94)  [7aNa7v8... -- 4sjsdBV...]
 
 DEBUG [nio-worker-group-3-8] c.t.n.WriteErrorHandler - [c3226df0 first.public.ip:6864] Write failed 
 (com.wavesplatform.network.GetSignatures)
 io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't send message GetSignatures((total=94) 
 [7aNa7v8... -- 4sjsdBV...]) to ChannelHandlerContext(MessageCodec#0, [id: 0xc3226df0, L:/second.public.ip:40750 - 
 R:/first.public.ip:6864]) (unsupported)
 
      at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104)
 ```
 
 Could someone clue me in as to what is going wrong here?

**Comment by iwansurya** [comment]
No idea

**Comment by DrBlast** [comment]
@affiliatepayday can you post whole error stacktrace?

**Comment by affiliatepayday** [comment]
@DrBlast sorry for my delay.

```
2021-05-01 14:25:16,296 DEBUG [rx-extension-loader-43] c.t.n.RxExtensionLoader$ - [44d30899 public.ip.server1:6864] Requesting signatures, last 93 are (total=93) [8J7sZah... -- 4sjsdBV...]
2021-05-01 14:25:16,301 DEBUG [nio-worker-group-3-2] c.t.n.WriteErrorHandler - [44d30899 public.ip.server1:6864] Write failed (com.wavesplatform.network.GetSignatures)
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't send message GetSignatures((total=93) [8J7sZah... -- 4sjsdBV...]) to ChannelHandlerContext(MessageCodec#0, [id: 0x44d30899, L:/public.ip.server2:36154 - R:/public.ip.server1:6864]) (unsupported)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104)
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
        at com.wavesplatform.network.TrafficLogger.write(TrafficLogger.scala:35)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
        at com.wavesplatform.network.WriteErrorHandler.write(WriteErrorHandler.scala:14)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
        at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Can't send message GetSignatures((total=93) [8J7sZah... -- 4sjsdBV...]) to ChannelHandlerContext(MessageCodec#0, [id: 0x44d30899, L:/public.ip.server2:36154 - R:/public.ip.server1:6864]) (unsupported)
        at com.wavesplatform.network.MessageCodec.encode(MessageCodec.scala:48)
        at com.wavesplatform.network.MessageCodec.encode(MessageCodec.scala:14)
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
        ... 22 common frames omitted
```

After this it just repeats for every block  BlockAppendError(Block is not a child of the last block...

**Comment by affiliatepayday** [comment]
I solved this problem, no one other than me should ever have this problem so I would prefer not to post what the solution was.
