### ISSUE TITLE
After update to v1.3.8 node goes on collecting blocks but does not log or sign blocks

### ISSUE THREAD

**Issue by sargatxet** [wavesplatform/Waves#3551]
I get this error and after that logs does not work any more:

`2021-09-26 19:21:06,796 DEBUG [appender-31] c.w.mining.MinerImpl - Next attempt for acc=3P5KC6qJH9TjDdQfgnvP1FpAg2Wa551JZEC in 657,337 seconds (19:32:04.131306)
2021-09-26 19:21:07,623 INFO  [main] c.w.Application - REST API was bound on 0.0.0.0:6869
2021-09-26 19:21:07,838 DEBUG [nio-worker-group-3-2] c.w.n.PeerDatabaseImpl - Suspending [1a6ef630 167.99.216.145:6868]
2021-09-26 19:21:08,726 DEBUG [nio-worker-group-3-4] c.w.n.PeerDatabaseImpl - Suspending [a1d30fc5 217.168.76.86:6868]
2021-09-26 19:21:09,949 INFO  [nio-worker-group-3-2] c.w.n.HandshakeHandler$Client - [a29b171d 103.161.184.175:6868] Accepted handshake Handshake(wavesW,(0,14,4),bolinchain.tech,1292626,Some(/103.161.184.175:6868))
2021-09-26 19:21:10,886 DEBUG [nio-worker-group-3-4] c.w.n.FatalErrorHandler - [687a46bd 104.131.48.151:6868] Exception caught
java.io.IOException: Conexión reinicializada por la máquina remota
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1134)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-09-26 19:21:10,888 DEBUG [nio-worker-group-3-4] c.w.n.PeerDatabaseImpl - Suspending [687a46bd 104.131.48.151:6868]
2021-09-26 19:21:17,635 INFO  [shutdownHook3] c.w.Application - Closing REST API
2021-09-26 19:21:17,648 DEBUG [shutdownHook3] c.w.Application - Closing peer database
2021-09-26 19:21:17,649 INFO  [shutdownHook3] c.w.n.PeerDatabaseImpl - Saving 162 known peer(s) to peers.dat
2021-09-26 19:21:17,666 DEBUG [shutdownHook2] c.w.u.SystemInformationReporter$ - Available processors: 2
Max memory available: 2147483648
os.name: Linux
os.version: 5.4.0-86-generic
os.arch: amd64
java.version: 11.0.11
java.vendor: Ubuntu
java.home: /usr/lib/jvm/java-11-openjdk-amd64
java.class.path: /usr/share/waves/lib/com.wavesplatform.waves-1.3.6.jar:/usr/share/waves/lib/com.wavesplatform.lang-1.3.6.jar:/usr/share/waves/lib/org.typelevel.machinist_2.13-0.6.8.jar:/usr/share/waves/lib/com.wavesplatform.leveldb-jna.leveldb-jna-native-1.22.3.jar:/usr/share/waves/lib/org.bouncycastle.bcpkix-jdk15on-1.59.jar:/usr/share/waves/lib/com.google.errorprone.error_prone_annotations-2.2.0.jar:/usr/share/waves/lib/com.typesafe.play.play-functional_2.13-2.9.0.jar:/usr/share/waves/lib/io.monix.monix-eval_2.13-3.3.0.jar:/usr/share/waves/lib/org.influxdb.influxdb-java-2.14.jar:/usr/share/waves/lib/org.iq80.leveldb.leveldb-api-0.12.jar:/usr/share/waves/lib/org.scala-lang.modules.scala-java8-compat_2.13-0.9.0.jar:/usr/share/waves/lib/com.softwaremill.sttp.core_2.13-1.6.4.jar:/usr/share/waves/lib/com.typesafe.play.play-json_2.13-2.9.0.jar:/usr/share/waves/lib/org.msgpack.msgpack-core-0.8.16.jar:/usr/share/waves/lib/io.netty.netty-handler-4.1.59.Final.jar:/usr/share/waves/lib/org.scala-lang.scala-library-2.13.3.jar:/usr/share/waves/lib/com.typesafe.akka.akka-stream_2.13-2.6.4.jar:/usr/share/waves/lib/net.java.dev.jna.jna-platform-5.5.0.jar:/usr/share/waves/lib/com.fasterxml.jackson.core.jackson-core-2.11.0.jar:/usr/share/waves/lib/com.wavesplatform.leveldb-jna.leveldb-jna-core-1.22.3.jar:/usr/share/waves/lib/org.scala-lang.modules.scala-parser-combinators_2.13-1.1.2.jar:/usr/share/waves/lib/com.typesafe.scala-logging.scala-logging_2.13-3.9.2.jar:/usr/share/waves/lib/com.typesafe.akka.akka-actor_2.13-2.6.4.jar:/usr/share/waves/lib/org.reactivestreams.reactive-streams-1.0.2.jar:/usr/share/waves/lib/io.monix.monix-execution_2.13-3.3.0.jar:/usr/share/waves/lib/com.thesamet.scalapb.scalapb-runtime_2.13-0.9.0.jar:/usr/share/waves/lib/ch.qos.logback.logback-classic-1.2.3.jar:/usr/share/waves/lib/com.typesafe.akka.akka-parsing_2.13-10.1.12.jar:/usr/share/waves/lib/io.kamon.kamon-core_2.13-2.1.0.jar:/usr/share/waves/lib/com.squareup.okio.okio-1.14.0.jar:/usr/share/waves/lib/com.typesafe.akka.akka-protobuf-v3_2.13-2.6.4.jar:/usr/share/waves/lib/org.apache.commons.commons-lang3-3.9.jar:/usr/share/waves/lib/com.google.code.findbugs.jsr305-3.0.2.jar:/usr/share/waves/lib/com.chuusai.shapeless_2.13-2.3.3.jar:/usr/share/waves/lib/io.monix.monix-internal-jctools_2.13-3.3.0.jar:/usr/share/waves/lib/com.fasterxml.jackson.core.jackson-databind-2.11.0.jar:/usr/share/waves/lib/org.typelevel.cats-effect_2.13-2.1.3.jar:/usr/share/waves/lib/org.typelevel.cats-macros_2.13-2.1.0.jar:/usr/share/waves/lib/io.circe.circe-core_2.13-0.13.0.jar:/usr/share/waves/lib/com.google.guava.listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/usr/share/waves/lib/com.wavesplatform.zwaves-bn256-0.1.5-SNAPSHOT.jar:/usr/share/waves/lib/io.netty.netty-buffer-4.1.59.Final.jar:/usr/share/waves/lib/com.squareup.retrofit2.retrofit-2.4.0.jar:/usr/share/waves/lib/com.google.guava.guava-27.0.1-jre.jar:/usr/share/waves/lib/io.netty.netty-resolver-4.1.59.Final.jar:/usr/share/waves/lib/io.circe.circe-generic_2.13-0.13.0.jar:/usr/share/waves/lib/com.lihaoyi.fastparse_2.13-2.2.4.jar:/usr/share/waves/lib/com.thesamet.scalapb.scalapb-json4s_2.13-0.9.3.jar:/usr/share/waves/lib/com.fasterxml.jackson.core.jackson-annotations-2.11.0.jar:/usr/share/waves/lib/org.checkerframework.checker-qual-2.5.2.jar:/usr/share/waves/lib/com.lihaoyi.geny_2.13-0.5.1.jar:/usr/share/waves/lib/com.google.j2objc.j2objc-annotations-1.1.jar:/usr/share/waves/lib/com.google.protobuf.protobuf-java-3.10.0.jar:/usr/share/waves/lib/net.logstash.logback.logstash-logback-encoder-4.11.jar:/usr/share/waves/lib/com.wavesplatform.zwaves-0.1.0-SNAPSHOT.jar:/usr/share/waves/lib/com.typesafe.akka.akka-slf4j_2.13-2.6.4.jar:/usr/share/waves/lib/com.lihaoyi.sourcecode_2.13-0.2.1.jar:/usr/share/waves/lib/org.slf4j.slf4j-api-1.7.25.jar:/usr/share/waves/lib/ch.obermuhlner.big-math-2.1.0.jar:/usr/share/waves/lib/org.rudogma.supertagged_2.13-1.5.jar:/usr/share/waves/lib/org.web3j.utils-4.5.18.jar:/usr/share/waves/lib/io.monix.monix-catnap_2.13-3.3.0.jar:/usr/share/waves/lib/io.circe.circe-numbers_2.13-0.13.0.jar:/usr/share/waves/lib/org.json4s.json4s-core_2.13-3.6.7.jar:/usr/share/waves/lib/org.typelevel.cats-kernel_2.13-2.1.0.jar:/usr/share/waves/lib/com.fasterxml.jackson.datatype.jackson-datatype-jsr310-2.10.4.jar:/usr/share/waves/lib/com.typesafe.akka.akka-http_2.13-10.1.12.jar:/usr/share/waves/lib/org.parboiled.parboiled_2.13-2.1.8.jar:/usr/share/waves/lib/org.typelevel.cats-mtl-core_2.13-0.7.1.jar:/usr/share/waves/lib/org.typelevel.jawn-parser_2.13-1.0.0.jar:/usr/share/waves/lib/com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.10.4.jar:/usr/share/waves/lib/com.google.guava.failureaccess-1.0.1.jar:/usr/share/waves/lib/io.netty.netty-codec-4.1.59.Final.jar:/usr/share/waves/lib/org.scorexfoundation.scorex-util_2.13-0.1.7.jar:/usr/share/waves/lib/com.squareup.moshi.moshi-1.5.0.jar:/usr/share/waves/lib/io.circe.circe-jawn_2.13-0.13.0.jar:/usr/share/waves/lib/org.json4s.json4s-jackson_2.13-3.6.7.jar:/usr/share/waves/lib/com.typesafe.akka.akka-http-core_2.13-10.1.12.jar:/usr/share/waves/lib/org.bouncycastle.bcprov-jdk15on-1.59.jar:/usr/share/waves/lib/org.web3j.rlp-4.5.18.jar:/usr/share/waves/lib/com.typesafe.ssl-config-core_2.13-0.4.1.jar:/usr/share/waves/lib/org.codehaus.mojo.animal-sniffer-annotations-1.17.jar:/usr/share/waves/lib/com.iheart.ficus_2.13-1.4.7.jar:/usr/share/waves/lib/com.typesafe.config-1.3.3.jar:/usr/share/waves/lib/org.codehaus.janino.commons-compiler-3.0.12.jar:/usr/share/waves/lib/org.web3j.abi-4.5.18.jar:/usr/share/waves/lib/org.json4s.json4s-scalap_2.13-3.6.7.jar:/usr/share/waves/lib/com.github.scopt.scopt_2.13-4.0.0-RC2.jar:/usr/share/waves/lib/io.netty.netty-transport-4.1.59.Final.jar:/usr/share/waves/lib/io.circe.circe-parser_2.13-0.13.0.jar:/usr/share/waves/lib/commons-net.commons-net-3.6.jar:/usr/share/waves/lib/com.thoughtworks.paranamer.paranamer-2.8.jar:/usr/share/waves/lib/io.monix.monix-reactive_2.13-3.3.0.jar:/usr/share/waves/lib/org.bitlet.weupnp-0.1.4.jar:/usr/share/waves/lib/net.java.dev.jna.jna-5.5.0.jar:/usr/share/waves/lib/org.typelevel.cats-core_2.13-2.1.0.jar:/usr/share/waves/lib/io.kamon.kamon-system-metrics_2.13-2.1.0.jar:/usr/share/waves/lib/com.squareup.okhttp3.logging-interceptor-3.11.0.jar:/usr/share/waves/lib/com.github.oshi.oshi-core-4.2.1.jar:/usr/share/waves/lib/org.web3j.crypto-4.5.18.jar:/usr/share/waves/lib/org.json4s.json4s-ast_2.13-3.6.7.jar:/usr/share/waves/lib/com.wavesplatform.curve25519-java-0.6.4.jar:/usr/share/waves/lib/org.scorexfoundation.scrypto_2.13-2.1.8.jar:/usr/share/waves/lib/com.squareup.retrofit2.converter-moshi-2.4.0.jar:/usr/share/waves/lib/org.apache.commons.commons-math3-3.6.1.jar:/usr/share/waves/lib/io.netty.netty-common-4.1.59.Final.jar:/usr/share/waves/lib/org.codehaus.janino.janino-3.0.12.jar:/usr/share/waves/lib/com.thesamet.scalapb.lenses_2.13-0.9.0.jar:/usr/share/waves/lib/ch.qos.logback.logback-core-1.2.3.jar:/usr/share/waves/lib/io.kamon.kamon-influxdb_2.13-2.1.0.jar:/usr/share/waves/lib/com.squareup.okhttp3.okhttp-3.11.0.jar:/usr/share/waves/lib/com.github.spullara.mustache.java.compiler-0.9.5.jar:/usr/share/waves/lib/org.scala-lang.scala-reflect-2.13.3.jar:/usr/share/waves/lib/io.monix.implicitbox_2.13-0.2.0.jar:/usr/share/waves/lib/org.web3j.abi-4.5.18.jar:/usr/share/waves/lib/com.lihaoyi.sourcecode_2.13-0.2.1.jar:/usr/share/waves/lib/com.typesafe.akka.akka-slf4j_2.13-2.6.4.jar:/usr/share/waves/lib/com.iheart.ficus_2.13-1.4.7.jar:/usr/share/waves/lib/com.lihaoyi.fastparse_2.13-2.2.4.jar:/usr/share/waves/lib/org.apache.commons.commons-lang3-3.9.jar:/usr/share/waves/lib/org.scala-lang.modules.scala-java8-compat_2.13-0.9.0.jar:/usr/share/waves/lib/net.logstash.logback.logstash-logback-encoder-4.11.jar:/usr/share/waves/lib/org.slf4j.slf4j-api-1.7.25.jar:/usr/share/waves/lib/org.typelevel.cats-mtl-core_2.13-0.7.1.jar:/usr/share/waves/lib/com.wavesplatform.leveldb-jna.leveldb-jna-native-1.22.3.jar:/usr/share/waves/lib/com.fasterxml.jackson.core.jackson-databind-2.11.0.jar:/usr/share/waves/lib/com.thoughtworks.paranamer.paranamer-2.8.jar:/usr/share/waves/lib/io.netty.netty-resolver-4.1.59.Final.jar:/usr/share/waves/lib/com.google.errorprone.error_prone_annotations-2.2.0.jar:/usr/share/waves/lib/org.typelevel.cats-effect_2.13-2.1.3.jar:/usr/share/waves/lib/com.google.guava.listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/usr/share/waves/lib/io.netty.netty-buffer-4.1.59.Final.jar:/usr/share/waves/lib/io.netty.netty-handler-4.1.59.Final.jar:/usr/share/waves/lib/org.reactivestreams.reactive-streams-1.0.2.jar:/usr/share/waves/lib/io.netty.netty-common-4.1.59.Final.jar:/usr/share/waves/lib/com.fasterxml.jackson.core.jackson-core-2.11.0.jar:/usr/share/waves/lib/com.squareup.retrofit2.retrofit-2.4.0.jar:/usr/share/waves/lib/ch.obermuhlner.big-math-2.1.0.jar:/usr/share/waves/lib/org.parboiled.parboiled_2.13-2.1.8.jar:/usr/share/waves/lib/org.bouncycastle.bcprov-jdk15on-1.59.jar:/usr/share/waves/lib/io.netty.netty-codec-4.1.59.Final.jar:/usr/share/waves/lib/com.google.guava.guava-27.0.1-jre.jar:/usr/share/waves/lib/org.apache.commons.commons-math3-3.6.1.jar:/usr/share/waves/lib/org.checkerframework.checker-qual-2.5.2.jar:/usr/share/waves/lib/org.msgpack.msgpack-core-0.8.16.jar:/usr/share/waves/lib/com.squareup.okhttp3.okhttp-3.11.0.jar:/usr/share/waves/lib/io.netty.netty-transport-4.1.59.Final.jar:/usr/share/waves/lib/org.web3j.utils-4.5.18.jar:/usr/share/waves/lib/io.circe.circe-jawn_2.13-0.13.0.jar:/usr/share/waves/lib/io.circe.circe-numbers_2.13-0.13.0.jar:/usr/share/waves/lib/com.thesamet.scalapb.lenses_2.13-0.9.0.jar:/usr/share/waves/lib/com.typesafe.akka.akka-parsing_2.13-10.1.12.jar:/usr/share/waves/lib/com.typesafe.play.play-json_2.13-2.9.0.jar:/usr/share/waves/lib/com.github.spullara.mustache.java.compiler-0.9.5.jar:/usr/share/waves/lib/org.iq80.leveldb.leveldb-api-0.12.jar:/usr/share/waves/lib/org.typelevel.cats-macros_2.13-2.1.0.jar:/usr/share/waves/lib/com.github.scopt.scopt_2.13-4.0.0-RC2.jar:/usr/share/waves/lib/com.typesafe.scala-logging.scala-logging_2.13-3.9.2.jar:/usr/share/waves/lib/org.web3j.rlp-4.5.18.jar:/usr/share/waves/lib/org.scorexfoundation.scrypto_2.13-2.1.8.jar:/usr/share/waves/lib/org.typelevel.jawn-parser_2.13-1.0.0.jar:/usr/share/waves/lib/com.wavesplatform.waves-1.3.6.jar:/usr/share/waves/lib/com.wavesplatform.lang-1.3.6.jar:/usr/share/waves/lib/org.json4s.json4s-ast_2.13-3.6.7.jar:/usr/share/waves/lib/org.scala-lang.scala-reflect-2.13.3.jar:/usr/share/waves/lib/io.monix.implicitbox_2.13-0.2.0.jar:/usr/share/waves/lib/com.chuusai.shapeless_2.13-2.3.3.jar:/usr/share/waves/lib/com.softwaremill.sttp.core_2.13-1.6.4.jar:/usr/share/waves/lib/com.typesafe.play.play-functional_2.13-2.9.0.jar:/usr/share/waves/lib/org.rudogma.supertagged_2.13-1.5.jar:/usr/share/waves/lib/com.typesafe.ssl-config-core_2.13-0.4.1.jar:/usr/share/waves/lib/org.json4s.json4s-core_2.13-3.6.7.jar:/usr/share/waves/lib/com.typesafe.akka.akka-actor_2.13-2.6.4.jar:/usr/share/waves/lib/org.bouncycastle.bcpkix-jdk15on-1.59.jar:/usr/share/waves/lib/io.monix.monix-eval_2.13-3.3.0.jar:/usr/share/waves/lib/com.typesafe.akka.akka-protobuf-v3_2.13-2.6.4.jar:/usr/share/waves/lib/io.kamon.kamon-system-metrics_2.13-2.1.0.jar:/usr/share/waves/lib/com.wavesplatform.leveldb-jna.leveldb-jna-core-1.22.3.jar:/usr/share/waves/lib/com.google.guava.failureaccess-1.0.1.jar:/usr/share/waves/lib/org.scala-lang.modules.scala-parser-combinators_2.13-1.1.2.jar:/usr/share/waves/lib/org.typelevel.cats-kernel_2.13-2.1.0.jar:/usr/share/waves/lib/io.kamon.kamon-core_2.13-2.1.0.jar:/usr/share/waves/lib/com.fasterxml.jackson.datatype.jackson-datatype-jsr310-2.10.4.jar:/usr/share/waves/lib/org.scala-lang.scala-library-2.13.3.jar:/usr/share/waves/lib/org.codehaus.mojo.animal-sniffer-annotations-1.17.jar:/usr/share/waves/lib/com.typesafe.config-1.3.3.jar:/usr/share/waves/lib/com.google.j2objc.j2objc-annotations-1.1.jar:/usr/share/waves/lib/io.monix.monix-execution_2.13-3.3.0.jar:/usr/share/waves/lib/io.monix.monix-reactive_2.13-3.3.0.jar:/usr/share/waves/lib/io.monix.monix-internal-jctools_2.13-3.3.0.jar:/usr/share/waves/lib/org.typelevel.machinist_2.13-0.6.8.jar:/usr/share/waves/lib/com.wavesplatform.zwaves-0.1.0-SNAPSHOT.jar:/usr/share/waves/lib/commons-net.commons-net-3.6.jar:/usr/share/waves/lib/com.squareup.retrofit2.converter-moshi-2.4.0.jar:/usr/share/waves/lib/io.circe.circe-core_2.13-0.13.0.jar:/usr/share/waves/lib/io.monix.monix-catnap_2.13-3.3.0.jar:/usr/share/waves/lib/com.wavesplatform.curve25519-java-0.6.4.jar:/usr/share/waves/lib/org.json4s.json4s-scalap_2.13-3.6.7.jar:/usr/share/waves/lib/org.typelevel.cats-core_2.13-2.1.0.jar:/usr/share/waves/lib/net.java.dev.jna.jna-5.5.0.jar:/usr/share/waves/lib/com.fasterxml.jackson.core.jackson-annotations-2.11.0.jar:/usr/share/waves/lib/org.web3j.crypto-4.5.18.jar:/usr/share/waves/lib/com.thesamet.scalapb.scalapb-json4s_2.13-0.9.3.jar:/usr/share/waves/lib/com.squareup.okio.okio-1.14.0.jar:/usr/share/waves/lib/ch.qos.logback.logback-classic-1.2.3.jar:/usr/share/waves/lib/com.wavesplatform.zwaves-bn256-0.1.5-SNAPSHOT.jar:/usr/share/waves/lib/com.google.code.findbugs.jsr305-3.0.2.jar:/usr/share/waves/lib/org.influxdb.influxdb-java-2.14.jar:/usr/share/waves/lib/com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.10.4.jar:/usr/share/waves/lib/org.bitlet.weupnp-0.1.4.jar:/usr/share/waves/lib/com.typesafe.akka.akka-stream_2.13-2.6.4.jar:/usr/share/waves/lib/com.thesamet.scalapb.scalapb-runtime_2.13-0.9.0.jar:/usr/share/waves/lib/com.typesafe.akka.akka-http_2.13-10.1.12.jar:/usr/share/waves/lib/com.lihaoyi.geny_2.13-0.5.1.jar:/usr/share/waves/lib/io.circe.circe-parser_2.13-0.13.0.jar:/usr/share/waves/lib/io.kamon.kamon-influxdb_2.13-2.1.0.jar:/usr/share/waves/lib/com.google.protobuf.protobuf-java-3.10.0.jar:/usr/share/waves/lib/io.circe.circe-generic_2.13-0.13.0.jar:/usr/share/waves/lib/org.scorexfoundation.scorex-util_2.13-0.1.7.jar:/usr/share/waves/lib/org.codehaus.janino.janino-3.0.12.jar:/usr/share/waves/lib/org.json4s.json4s-jackson_2.13-3.6.7.jar:/usr/share/waves/lib/net.java.dev.jna.jna-platform-5.5.0.jar:/usr/share/waves/lib/com.squareup.okhttp3.logging-interceptor-3.11.0.jar:/usr/share/waves/lib/org.codehaus.janino.commons-compiler-3.0.12.jar:/usr/share/waves/lib/ch.qos.logback.logback-core-1.2.3.jar:/usr/share/waves/lib/com.squareup.moshi.moshi-1.5.0.jar:/usr/share/waves/lib/com.github.oshi.oshi-core-4.2.1.jar:/usr/share/waves/lib/com.typesafe.akka.akka-http-core_2.13-10.1.12.jar
user.dir: /
sun.net.inetaddr.ttl: 0
sun.net.inetaddr.negative.ttl: 0
networkaddress.cache.ttl: null
networkaddress.cache.negative.ttl: null
Configuration: {"metrics":{"collect-responsiveness-metrics":"off","create-responsiveness-csv":"off","enable":"no","node-id":-1,"responsiveness-metrics-retention-policy":""},"waves":{"blockchain":{"custom":{"address-scheme-character":"C","functionality":{"block-version-3-after-height":0,"blocks-for-feature-activation":9000,"delay-delta":8,"feature-check-blocks-period":10000,"generation-balance-depth-from-50-to-1000-after-height":0,"lease-expiration":1000000,"max-transaction-time-back-offset":"120m","max-transaction-time-forward-offset":"90m","min-block-time":"15s","pre-activated-features":{},"reset-effective-balances-at-height":0},"genesis":{"average-block-delay":"60s","initial-balance":100000000000000,"initial-base-target":153722867,"signature":"BASE58BLOCKSIGNATURE","timestamp":1460678400000,"transactions":[{"amount":50000000000000,"recipient":"BASE58ADDRESS1"},{"amount":50000000000000,"recipient":"BASE58ADDRESS2"}]},"rewards":{"initial":600000000,"min-increment":50000000,"term":100000,"voting-interval":10000}},"type":"mainnet"},"config":{"directory":"/etc/waves"},"db":{"directory":"/var/lib/waves/data","max-cache-size":100000,"max-rollback-depth":2000,"remember-blocks":"3h","store-invoke-script-results":true,"store-state-hashes":false,"store-transactions-by-address":true,"use-bloom-filter":false},"defaults":{"blockchain":{"type":"mainnet"},"config":{"directory":"/etc/waves"},"custom":{},"devnet":{"blockchain":{"custom":{"address-scheme-character":"D","functionality":{"block-version-3-after-height":0,"blocks-for-feature-activation":4,"double-features-periods-after-height":1000000000,"feature-check-blocks-period":5,"generation-balance-depth-from-50-to-1000-after-height":0,"last-time-based-fork-parameter":1492128000000,"lease-expiration":1000000,"max-transaction-time-back-offset":"120m","max-transaction-time-forward-offset":"90m","min-asset-info-update-interval":7,"pre-activated-features":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0,"14":0,"15":0},"reset-effective-balances-at-height":4650},"genesis":{"average-block-delay":"1m","block-timestamp":1489352400000,"initial-balance":7700000000000000,"initial-base-target":100,"signature":"5ASUNefZs2dLRroid7LPS24PL85K5Y6WZqA1bfQGCHxkfhLK39jHDUpmFzELKQ66AHCm7ZhQVwpF6G95tat3xfpr","timestamp":1489352400000,"transactions":[{"amount":2500000000000000,"recipient":"3FR3MyuXumwBj1bLC8xnW38iHtwm9Ugdm8K"},{"amount":200000000000000,"recipient":"3FgScYB6MNdnN8m4xXddQe1Bjkwmd3U7YtM"},{"amount":1000000000000000,"recipient":"3FWXhvWq2r8m54MmCEZ3YZkLg2qUdGWbU3V"},{"amount":500000000000000,"recipient":"3FkBWsgT9T3snZ4ZpzzQCJWQngJBLdDEPfU"},{"amount":1500000000000000,"recipient":"3FeeqPbaEUQ8h3eQ4ZX9WcqzqskGbfTqM2a"},{"amount":2000000000000000,"recipient":"3FcSgww3tKZ7feQVmcnPFmRxsjqBodYz63x"}]},"rewards":{"initial":600000000,"min-increment":50000000,"term":100000,"voting-interval":10000}},"type":"CUSTOM"},"kamon":{"enable":"yes","metric":{"tick-interval":"5s"},"util":{"filters":{"akka.tracked-dispatcher":{"includes":["wavesplatform/**"]},"tx-processing":{"includes":["tx.**"]}}}},"miner":{"interval-after-last-block-then-generation-is-allowed":"15d"},"network":{"known-peers":["116.203.58.211:6864","94.130.231.52:6864","116.203.110.73:6864","116.203.102.150:6864"],"port":6864},"rest-api":{"api-key-different-host":"yes","api-key-hash":"7B74gZMpdzQSB45A7KRwKW6mDUYaWhFY8kWh5qiLRRoA"},"synchronization":{"synchronization-timeout":"120s"},"wallet":{"file":null,"seed":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"}},"directory":"/var/lib/waves","mainnet":{"network":{"known-peers":["168.119.116.189:6868","135.181.87.72:6868","35.158.218.156:6868","52.48.34.89:6868"],"port":6868},"rest-api":{"bind-address":"127.0.0.1"}},"stagenet":{"network":{"known-peers":["88.99.185.128:6868","95.216.205.3:6868","49.12.15.166:6868","88.198.179.16:6868"],"port":6862}},"testnet":{"network":{"known-peers":["159.69.126.149:6868","94.130.105.239:6868","159.69.126.153:6868","94.130.172.201:6868"],"port":6863}}},"directory":"/var/lib/waves","extensions":[],"extensions-shutdown-timeout":"5 minutes","features":{"auto-shutdown-on-unsupported-feature":"yes","supported":[]},"miner":{"enable":"yes","interval-after-last-block-then-generation-is-allowed":"1d","max-transactions-in-micro-block":255,"micro-block-interval":"5s","min-micro-block-age":"2s","minimal-block-generation-offset":0,"no-quorum-mining-delay":"5s","quorum":1},"network":{"bind-address":"0.0.0.0","black-list-residence-time":"15m","break-idle-connections-timeout":"5m","connection-timeout":"30s","enable-blacklisting":"yes","enable-peers-exchange":"yes","file":"/var/lib/waves/peers.dat","handshake-timeout":"30s","known-peers":["168.119.116.189:6868","135.181.87.72:6868","35.158.218.156:6868","52.48.34.89:6868"],"max-inbound-connections":100,"max-outbound-connections":100,"max-single-host-connections":3,"max-unverified-peers":100,"node-name":"SargaPool","peers-broadcast-interval":"2m","peers-data-residence-time":"1d","port":6868,"received-txs-cache-timeout":"3m","suspension-residence-time":"1m","traffic-logger":{"ignore-rx-messages":[1,2,25],"ignore-tx-messages":[1,2,23,25,26,29,30]},"upnp":{"discover-timeout":"3s","enable":"no","gateway-timeout":"7s"}},"ntp-server":"pool.ntp.org","rest-api":{"api-key-different-host":"no","bind-address":"0.0.0.0","cors":"yes","distribution-address-limit":1000,"enable":"yes","evaluate-script-complexity-limit":26000,"limited-pool-threads":2,"port":6869,"transactions-by-address-limit":1000},"rewards":{},"synchronization":{"history-replier":{"max-block-cache-size":20,"max-micro-block-cache-size":50},"invalid-blocks-storage":{"max-size":30000,"timeout":"5m"},"max-rollback":100,"micro-block-synchronizer":{"inv-cache-timeout":"45s","processed-micro-blocks-cache-timeout":"3m","wait-response-timeout":"2s"},"score-ttl":"90s","synchronization-timeout":"60s","utx-synchronizer":{"allow-tx-rebroadcasting":"yes","max-queue-size":5000,"max-threads":8,"network-tx-cache-size":1000000}},"utx":{"allow-blacklisted-transfer-to":[],"allow-skip-checks":true,"allow-transactions-from-smart-accounts":true,"blacklist-sender-addresses":[],"fast-lane-addresses":[],"max-bytes-size":52428800,"max-scripted-size":5000,"max-size":100000}}}
2021-09-26 19:21:17,677 WARN  [ctor.default-dispatcher-6] a.a.CoordinatedShutdown - Could not addJvmShutdownHook, due to: Shutdown in progress
2021-09-26 19:21:17,699 DEBUG [shutdownHook3] c.w.Application - Node's actor system shutdown successful
2021-09-26 19:21:17,701 INFO  [shutdownHook3] c.w.Application - Stopping network services
2021-09-26 19:21:17,701 DEBUG [shutdownHook3] c.w.network.NetworkServer$ - Unbound server
2021-09-26 19:21:17,714 DEBUG [shutdownHook3] c.w.network.NetworkServer$ - Closed all channels
2021-09-26 19:21:21,739 DEBUG [shutdownHook3] c.w.Application - Shutting down Appender
2021-09-26 19:21:21,740 INFO  [shutdownHook3] c.w.Application - Appender was shutdown successfully
2021-09-26 19:21:21,741 INFO  [shutdownHook3] c.w.Application - Closing storage
2021-09-26 19:21:21,741 DEBUG [shutdownHook3] c.w.d.LevelDBWriter$ - Shutting down LevelDBWriter
2021-09-26 19:21:21,746 INFO  [shutdownHook3] c.w.Application - Shutdown complete
`

**Comment by sargatxet** [comment]
Found that logs has changed its location to /var/lib/waves/log

It's working.
