### ISSUE TITLE
v1.3.9 keep exit for "Negative transfer amount = -15220" at block 2871360

### ISSUE THREAD

**Issue by jun0tpyrc** [wavesplatform/Waves#3593]
**Describe the bug**
```
2021-11-25 08:58:13,250 ERROR [rx-extension-loader-48] c.w.Application - Error in Appender
com.wavesplatform.lang.v1.evaluator.RejectException: Negative transfer amount = -15220
        at com.wavesplatform.state.diffs.invoke.InvokeDiffsCommon$.$anonfun$checkScriptResultFields$1(InvokeDiffsCommon.scala:666)
        at com.wavesplatform.state.diffs.invoke.InvokeDiffsCommon$.$anonfun$checkScriptResultFields$1$adapted(InvokeDiffsCommon.scala:663)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at com.wavesplatform.state.diffs.invoke.InvokeDiffsCommon$.checkScriptResultFields(InvokeDiffsCommon.scala:663)
        at com.wavesplatform.state.diffs.invoke.InvokeScriptTransactionDiff$.$anonfun$evaluateV2$3(InvokeScriptTransactionDiff.scala:303)
        at scala.util.Either.map(Either.scala:382)
        at com.wavesplatform.state.diffs.invoke.InvokeScriptTransactionDiff$.evaluateV2(InvokeScriptTransactionDiff.scala:303)
        at com.wavesplatform.state.diffs.invoke.InvokeScriptTransactionDiff$.$anonfun$apply$4(InvokeScriptTransactionDiff.scala:103)
        at com.wavesplatform.metrics.TxProcessingStats$TxTimerExt$.measureForType$extension(TxProcessingStats.scala:26)
        at com.wavesplatform.state.diffs.invoke.InvokeScriptTransactionDiff$.executeMainScript$1(InvokeScriptTransactionDiff.scala:76)
        at com.wavesplatform.state.diffs.invoke.InvokeScriptTransactionDiff$.executeInvoke$1(InvokeScriptTransactionDiff.scala:133)
        at com.wavesplatform.state.diffs.invoke.InvokeScriptTransactionDiff$.$anonfun$apply$40(InvokeScriptTransactionDiff.scala:266)
        at com.wavesplatform.transaction.smart.script.trace.TracedResult.flatMap(TracedResult.scala:28)
        at com.wavesplatform.state.diffs.invoke.InvokeScriptTransactionDiff$.$anonfun$apply$30(InvokeScriptTransactionDiff.scala:225)
        at com.wavesplatform.transaction.smart.script.trace.TracedResult.flatMap(TracedResult.scala:28)
        at com.wavesplatform.state.diffs.invoke.InvokeScriptTransactionDiff$.$anonfun$apply$28(InvokeScriptTransactionDiff.scala:223)
        at com.wavesplatform.transaction.smart.script.trace.TracedResult.flatMap(TracedResult.scala:28)
        at com.wavesplatform.state.diffs.invoke.InvokeScriptTransactionDiff$.apply(InvokeScriptTransactionDiff.scala:222)
        at com.wavesplatform.state.diffs.TransactionDiffer$.$anonfun$transactionDiff$1(TransactionDiffer.scala:164)
...
```

**To Reproduce**
```
run v1.3.9
```

**Comment by phearnot** [comment]
Please upgrade to [v1.3.10](https://github.com/wavesplatform/Waves/releases/tag/v1.3.10) which fixes this issue.
