### ISSUE TITLE
Unable to connect to localhost machines (with v0.7.2)

### ISSUE THREAD

**Issue by devos50** [wavesplatform/Waves#427]
I'm trying to setup a small test network on a single machine. For this, I've created two configuration files, based on the shipped `waves-devnet.conf`. As indicated in the `network.port` section, I expect that a network process will listen on port 6864 for incoming connections. Starting the first nodes goes well (command: `java -jar waves-all-0.7.2.jar waves-devnet.conf`). However, when starting the second node (command: `java -jar waves-all-0.7.2.jar waves-devnet-2.conf`), I get the following error:

```
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6864
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused
	... 11 common frames omitted
```

Also, `netstat` does not indicate a listening port on 6864. I've added my first node to the list of known peers of the second node (`known-peers = ["127.0.0.1:6864"]`).

So am I missing some parameter here or is there something else wrong with my approach?

Any help would be greatly appreciated!

**Comment by alexeykiselev** [comment]
Have you set `waves.network.declared-address`? Without setting it to releasable value node won't open network port for incoming connections. In your case it should be set to 127.0.0.1:6864. And you should place the second node on other port.

**Comment by devos50** [comment]
@alexeykiselev great, that was the issue! Thanks for your help 👍
