### ISSUE TITLE
macOS Build failing

### ISSUE THREAD

**Issue by Cordo-van-Saviour** [wavesplatform/Waves#766]
I'm trying to install Waves, and I'm getting a following error:

```
Apples-MacBook-Pro:Waves-0.8.8 ookie$ sbt packageAll
[info] Loading project definition from /Users/ookie/Downloads/Waves-0.8.8/project
[info] Updating {file:/Users/ookie/Downloads/Waves-0.8.8/project/}waves-0-8-8-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 
[warn] 	* org.eclipse.sisu:org.eclipse.sisu.plexus:0.3.2 is selected over 0.3.0.M1
[warn] 	    +- org.apache.maven:maven-plugin-api:3.3.9            (depends on 0.3.2)
[warn] 	    +- org.apache.maven:maven-core:3.2.5                  (depends on 0.3.0.M1)
[warn] 
[warn] 	* org.codehaus.plexus:plexus-utils:3.0.22 is selected over {1.5.5, 3.0.20, 3.0.17}
[warn] 	    +- org.apache.maven:maven-artifact:3.3.9              (depends on 3.0.22)
[warn] 	    +- org.apache.maven:maven-model:3.3.9                 (depends on 3.0.22)
[warn] 	    +- org.eclipse.sisu:org.eclipse.sisu.plexus:0.3.2     (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-model-builder:3.2.5         (depends on 3.0.20)
[warn] 	    +- org.apache.maven:maven-settings-builder:3.2.5      (depends on 3.0.20)
[warn] 	    +- org.apache.maven:maven-repository-metadata:3.2.5   (depends on 3.0.20)
[warn] 	    +- org.apache.maven:maven-settings:3.2.5              (depends on 3.0.20)
[warn] 	    +- org.apache.maven:maven-aether-provider:3.2.5       (depends on 3.0.20)
[warn] 	    +- org.apache.maven:maven-core:3.2.5                  (depends on 3.0.20)
[warn] 	    +- org.sonatype.plexus:plexus-sec-dispatcher:1.3      (depends on 1.5.5)
[warn] 
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 2 Scala sources to /Users/ookie/Downloads/Waves-0.8.8/project/target/scala-2.10/sbt-0.13/classes...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Set current project to waves (in build file:/Users/ookie/Downloads/Waves-0.8.8/)
[success] Total time: 0 s, completed Dec 27, 2017 1:57:14 PM
[info] Updating {file:/Users/ookie/Downloads/Waves-0.8.8/}node...
[info] Resolving jline#jline;2.14.5 ...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 
[warn] 	* com.google.guava:guava:21.0 is selected over {19.0, 20.0}
[warn] 	    +- com.wavesplatform:waves:20171227T125713            (depends on 21.0)
[warn] 	    +- io.swagger:swagger-core:1.5.16                     (depends on 20.0)
[warn] 	    +- org.reflections:reflections:0.9.11                 (depends on 20.0)
[warn] 	    +- io.swagger:swagger-jaxrs:1.5.16                    (depends on 20.0)
[warn] 	    +- org.scorexfoundation:scrypto_2.12:1.2.2            (depends on 19.0)
[warn] 
[warn] Run 'evicted' to see detailed eviction warnings
scala.MatchError: 20171227T125713 (of class java.lang.String)
	at $7a9b79a89418bfc828ae$$anonfun$$sbtdef$1.apply(/Users/ookie/Downloads/Waves-0.8.8/build.sbt:57)
	at $7a9b79a89418bfc828ae$$anonfun$$sbtdef$1.apply(/Users/ookie/Downloads/Waves-0.8.8/build.sbt:54)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (node/compile:managedSources) scala.MatchError: 20171227T125713 (of class java.lang.String)
[error] Total time: 6 s, completed Dec 27, 2017 1:57:20 PM
```

I'm not that well versed in Scala and any help would be greatly appreciated!

**Comment by alexeykiselev** [comment]
The build depends on the presence of Git repository, but you are trying to build from the source's archive. Try to clone our master branch or release tag and build from it.
