### ISSUE TITLE
Not able to compile the code

### ISSUE THREAD

**Issue by khelle** [wavesplatform/Waves#771]
I am not able to compile the code under Ubuntu 16.04. I receive following errors:

```
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 
[warn] 	* com.google.guava:guava:21.0 is selected over {19.0, 20.0}
[warn] 	    +- com.wavesplatform:waves:20180102T165852            (depends on 21.0)
[warn] 	    +- io.swagger:swagger-core:1.5.16                     (depends on 20.0)
[warn] 	    +- org.reflections:reflections:0.9.11                 (depends on 20.0)
[warn] 	    +- io.swagger:swagger-jaxrs:1.5.16                    (depends on 20.0)
[warn] 	    +- org.scorexfoundation:scrypto_2.12:1.2.2            (depends on 19.0)
[warn] 
[warn] Run 'evicted' to see detailed eviction warnings
scala.MatchError: 20180102T165852 (of class java.lang.String)
	at $7ca4744d6744c656e23f$$anonfun$$sbtdef$1.apply(/home/waves/node/build.sbt:57)
	at $7ca4744d6744c656e23f$$anonfun$$sbtdef$1.apply(/home/waves/node/build.sbt:54)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (node/compile:managedSources) scala.MatchError: 20180102T165852 (of class java.lang.String)
[error] Total time: 118 s, completed Jan 2, 2018 6:00:51 PM
```

**Comment by alexeykiselev** [comment]
Please, clone the entire git repository. You have to build from working copy of it.

**Comment by khelle** [comment]
@alexeykiselev its exactly what I did.

**Comment by alexeykiselev** [comment]
Please post output of `git describe` executed in project folder
