### ISSUE TITLE
Exception while starting server

### ISSUE THREAD

**Issue by ashihaby** [wavesplatform/Waves#772]
I have to create a private Waves blockchain network according to this document https://github.com/wavesplatform/Waves/wiki/Creating-a-private-Waves-blockchain-network
But I got this error 

```
2018-01-04 21:14:14.292 INFO  [run-main-0] kamon.Kamon$Instance - Initializing Kamon...                                                            [66/3881]
2018-01-04 21:14:15.632 INFO  [lt-dispatcher-2] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2018-01-04 21:14:16.411 INFO  [lt-dispatcher-5] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2018-01-04 21:14:16.442 INFO  [run-main-0] c.w.Application$ - Waves v0.8.10-DIRTY Blockchain Id: Y
2018-01-04 21:14:28.264 INFO  [run-main-0] c.w.Application$$anon$1 - Node REST API was bound on 0.0.0.0:6861
2018-01-04 21:14:28.324 INFO  [run-main-0] c.w.s.BlockchainUpdaterImpl - State rebuild started, total persisted blocks: 102, [ in-memory: (Δh=0, Δtxs=0) ] $
 persisted: h=0
2018-01-04 21:14:28.473 ERROR [block-deser-49] c.w.s.diffs.BlockDiffer$ - Error executing task
java.util.NoSuchElementException: Either.right.get on Left
        at scala.util.Either$RightProjection.get(Either.scala:641)
        at scorex.transaction.GenesisTransaction$.$anonfun$parseTail$1(GenesisTransaction.scala:75)
        at scala.util.Try$.apply(Try.scala:209)
        at scorex.transaction.GenesisTransaction$.parseTail(GenesisTransaction.scala:65)
        at scorex.transaction.TransactionParser$.parseBytes(TransactionParser.scala:36)
        at scorex.block.Block$.$anonfun$transParseBytes$2(Block.scala:217)
        at scorex.block.Block$.$anonfun$transParseBytes$2$adapted(Block.scala:213)
        at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
        at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
        at scala.collection.immutable.Range.foreach(Range.scala:156)
        at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
        at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
        at scorex.block.Block$.$anonfun$transParseBytes$1(Block.scala:213)
        at scala.util.Try$.apply(Try.scala:209)
        at scorex.block.Block$.transParseBytes(Block.scala:202)
        at scorex.block.Block$.$anonfun$parseBytes$3(Block.scala:227)
        at scala.util.Success.flatMap(Try.scala:247)
        at scala.util.Try$WithFilter.flatMap(Try.scala:138)
        at scorex.block.Block$.parseBytes(Block.scala:226)
        at com.wavesplatform.state2.diffs.BlockDiffer$.$anonfun$unsafeDiffByRange$4(BlockDiffer.scala:78)
        at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:205)
        at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:127)
        at monix.eval.Task$$anon$2.run(Task.scala:1347)
        at monix.execution.internal.forkJoin.AdaptedForkJoinTask.exec(AdaptedForkJoinTask.scala:27)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) 
```

**Comment by alexeykiselev** [comment]
Looks like you haven't defined genesis transactions. Define at least one.
