### ISSUE TITLE
Private Chain

### ISSUE THREAD

**Issue by gelinger777** [wavesplatform/Waves#774]
```
[1]+  Stopped                 nano oschi-network.conf
ubuntu@instance-1:~/Waves$ sbt "run oschi-network.conf"
[info] Loading project definition from /home/ubuntu/Waves/project
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Set current project to waves (in build file:/home/ubuntu/Waves/)
[info] Running com.wavesplatform.Application oschi-network.conf
2018-01-06 11:41:07.023 INFO  [run-main-0] c.w.Application$ - Starting...
[error] (run-main-0) com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'waves.blockchain.custom.functionality.block-version-3-after-height'
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'waves.blockchain.custom.functionality.block-version-3-after-height'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getConfigNumber(SimpleConfig.java:219)
	at com.typesafe.config.impl.SimpleConfig.getInt(SimpleConfig.java:230)
	at net.ceedubs.ficus.readers.AnyValReaders$$anon$2.read(AnyValReaders.scala:11)
	at net.ceedubs.ficus.readers.AnyValReaders$$anon$2.read(AnyValReaders.scala:10)
	at com.wavesplatform.settings.BlockchainSettings$$anon$1.read(BlockchainSettings.scala:135)
	at com.wavesplatform.settings.BlockchainSettings$$anon$1.read(BlockchainSettings.scala:135)
	at net.ceedubs.ficus.FicusConfig.as(FicusConfig.scala:10)
	at net.ceedubs.ficus.FicusConfig.as$(FicusConfig.scala:10)
	at net.ceedubs.ficus.SimpleFicusConfig.as(FicusConfig.scala:19)
	at com.wavesplatform.settings.BlockchainSettings$.fromConfig(BlockchainSettings.scala:135)
	at com.wavesplatform.settings.WavesSettings$.fromConfig(WavesSettings.scala:36)
	at com.wavesplatform.Application$.main(Application.scala:280)
	at com.wavesplatform.Application.main(Application.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last node/compile:run for the full output.


but in json we have the variable . See the first part underneath. 





```

waves {
  # data storage folder
  directory=/tmp/custom

  logging-level = DEBUG

  blockchain {
    type: CUSTOM
    custom {
      address-scheme-character: "7"
      # various parameters of network consensus
      functionality {
        feature-check-blocks-period = 30
        blocks-for-feature-activation = 25
        allow-temporary-negative-until: 0
        allow-invalid-payment-transactions-by-timestamp: 0
        require-sorted-transactions-after: 0
        generation-balance-depth-from-50-to-1000-after-height: 0
        minimal-generating-balance-after: 0
        allow-transactions-from-future-until: 0
        allow-unissued-assets-until: 0
        require-payment-unique-id-after: 0
        allow-invalid-reissue-in-same-block-until-timestamp: 0
        allow-multiple-lease-cancel-transaction-until-timestamp: 0
        reset-effective-balances-at-height: 1
        allow-leased-balance-transfer-until: 0
        block-version-3-after: 0
        pre-activated-features = {
          2 = 0
        }
  
      }

genesis {
  average-block-delay: 60000ms
  initial-base-target: 153722867
  timestamp: 1500635421931
  block-timestamp: 1500635421931

```

**Comment by sebdei** [comment]
Add 
'block-version-3-after-height: 0'
to functionality

I can't tell you what it actually means
