### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by toanalien** [wavesplatform/Waves#805]
I tried to run a new private blockchain but got an error. 

```
toanalien@instance-1:~/Waves$ sbt "run waves-custom-network.conf"
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/toanalien/Waves/project
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Set current project to waves (in build file:/home/toanalien/Waves/)
[info] Updating ...
[info] Done updating.
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]  * com.google.guava:guava:21.0 is selected over {19.0, 20.0}
[warn]      +- com.wavesplatform:waves:0.9.1-11-g44985a6          (depends on 21.0)
[warn]      +- io.swagger:swagger-core:1.5.16                     (depends on 20.0)
[warn]      +- org.reflections:reflections:0.9.11                 (depends on 20.0)
[warn]      +- io.swagger:swagger-jaxrs:1.5.16                    (depends on 20.0)
[warn]      +- org.scorexfoundation:scrypto_2.12:1.2.2            (depends on 19.0)
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 1 Scala source to /home/toanalien/Waves/target/classes ...
[info] Done compiling.
[info] Packaging /home/toanalien/Waves/target/waves-0.9.1-11-g44985a6.jar ...
[info] Done packaging.
[info] Running com.wavesplatform.Application waves-custom-network.conf
2018-01-30 11:56:37,427 INFO  [run-main-0] c.w.Application$ - Starting...
2018-01-30 11:56:37,581 INFO  [run-main-0] kamon.Kamon$Instance - Initializing Kamon...
2018-01-30 11:56:37,801 INFO  [ctor.default-dispatcher-2] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2018-01-30 11:56:37,928 INFO  [ctor.default-dispatcher-2] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2018-01-30 11:56:37,933 INFO  [run-main-0] c.w.Application$ - Waves v0.9.1-11-g44985a6 Blockchain Id: T
[error] (run-main-0) java.lang.UnsatisfiedLinkError: org.fusesource.leveldbjni.internal.NativeOptions.init()V
[error] java.lang.UnsatisfiedLinkError: org.fusesource.leveldbjni.internal.NativeOptions.init()V
[error]         at org.fusesource.leveldbjni.internal.NativeOptions.init(Native Method)
[error]         at org.fusesource.leveldbjni.internal.NativeOptions.<clinit>(NativeOptions.java:54)
[error]         at org.fusesource.leveldbjni.JniDBFactory$OptionsResourceHolder.init(JniDBFactory.java:98)
[error]         at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:167)
[error]         at com.wavesplatform.db.package$.openDB(package.scala:22)
[error]         at com.wavesplatform.Application.<init>(Application.scala:53)
[error]         at com.wavesplatform.Application$$anon$1.<init>(Application.scala:314)
[error]         at com.wavesplatform.Application$.$anonfun$main$3(Application.scala:314)
[error]         at com.wavesplatform.Application$.$anonfun$main$3$adapted(Application.scala:288)
[error]         at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
[error]         at com.wavesplatform.Application$.main(Application.scala:288)
[error]         at com.wavesplatform.Application.main(Application.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.Run.invokeMain(Run.scala:93)
[error]         at sbt.Run.run0(Run.scala:87)
[error]         at sbt.Run.execute$1(Run.scala:65)
[error]         at sbt.Run.$anonfun$run$4(Run.scala:77)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error]         at sbt.TrapExit$App.run(TrapExit.scala:252)
[error]         at java.lang.Thread.run(Thread.java:748)
```

**Comment by alexeykiselev** [comment]
Closed with #806
