### ISSUE TITLE
java.lang.ArithmeticException

### ISSUE THREAD

**Issue by renickj** [wavesplatform/Waves#869]
Hi I have created a private chain with one additional node, I have added the address to the known servers, I am getting the below issue
Issue1:
2018-02-22 23:04:48.583 WARN  [tor.default-dispatcher-40] akka.actor.ActorSystemImpl - Illegal request, responding with status '400 Bad Request': Illegal HTTP message start
2018-02-22 23:04:52.427 DEBUG [nio-worker-group-3-5] c.w.n.PeerDatabaseImpl - Blacklisting [6734bb99 127.0.0.1:6861]: Timeout expired while waiting for handshake
Issue2:
2018-02-22 23:02:56.191 ERROR [appender-46] s.t.NgHistoryReader - java.lang.ArithmeticException: BigInteger divide by zero
	at java.math.MutableBigInteger.divideKnuth(Unknown Source)
	at java.math.BigInteger.divideKnuth(Unknown Source)
	at java.math.BigInteger.divide(Unknown Source)
	at scala.math.BigInt.$div(BigInt.scala:198)
	at scorex.block.Block.$anonfun$blockScore$1(Block.scala:154)

**Comment by phearnot** [comment]
This happens because you are mining with all the available balance, which quickly causes base target to become 0. We've fixed this issue in the master branch, but have not released a new version yet. For now, you can either build a node from sources, or make only a fraction of all the balance available for mining.
