### ISSUE TITLE
org.fusesource.leveldbjni.internal.NativeDB$DBException

### ISSUE THREAD

**Issue by kmn** [wavesplatform/Waves#963]
I updated fullnode upto verson 0.10.2 and 0.10.3 and I deleted all the `/var/lib/waves/data` 
But the nodes does not work.

Error message is followings.

What would be the issue?

```
2018-04-02 00:00:48,515 ERROR [main] c.w.actor.RootActorSystem$ - Error while initializing actor system wavesplatform
org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: error in middle of record
        at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
        at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218)
        at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168)
        at com.wavesplatform.db.package$.openDB(package.scala:23)
        at com.wavesplatform.Application.<init>(Application.scala:58)
        at com.wavesplatform.Application$.$anonfun$main$3(Application.scala:379)
        at com.wavesplatform.Application$.$anonfun$main$3$adapted(Application.scala:353)
        at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
        at com.wavesplatform.Application$.main(Application.scala:353)
        at com.wavesplatform.Application.main(Application.scala)
2018-04-02 00:00:48,531 DEBUG [shutdownHook1] c.w.u.SystemInformationReporter$ - Available processors: 4
Max memory available: 2147483648
os.name: Linux
os.version: 4.4.0-116-generic
os.arch: i386
java.version: 1.8.0_161
java.vendor: Oracle Corporation
```

**Comment by alexeykiselev** [comment]
You have a corrupted data chunk in your LevelDB.
Have you shut down the waves service before removing the data folder?
By the way, removing data wasn't necessary, I've mentioned it in the release notes.

To resolve the issue do following steps:
1. Stop waves service `sudo systemctl stop waves`
2. Remove data folder `sudo rm -rdf /var/lib/waves/data`
3. Start waves service `sudo systemctl start waves`

**Comment by kmn** [comment]
> Have you shut down the waves service before removing the data folder?

I did but the error occured again and again.

> By the way, removing data wasn't necessary, I've mentioned it in the release notes.
Thank you , I read the document and use mainnet-870000 data first .

**Comment by kmn** [comment]
dont close this issue yet.

**Comment by kmn** [comment]
I do sync data from  the genesis block again, and data sync suddenly stopped here.

```
2018-04-03 01:35:37,730 INFO  [appender-59] c.w.s.BlockchainUpdaterImpl - Block(cRntkXoV9hSrh41DrzE2FpE4vEM8pBj9uYhyTfLc7JBF1pgS2XmvPDLgKac9GjzRiz2C2UFYQRPTiQz79VxuXKf -> 4pPqZLC..., txs=8, features=Set()) appended. New height: 809545)
2018-04-03 01:35:37,730 DEBUG [rx-score-observer-55] c.w.n.RxScoreObserver$ - New local score: 107846212407808079835844, old: 107845919602346592382644, Δ292805461487453200
2018-04-03 01:35:37,738 INFO  [appender-59] c.w.s.BlockchainUpdaterImpl - After block application, total persisted blocks: 809545, [ in-memory: (Δh=98, Δtxs=3431) | (Δh=108, Δtxs=5979) ] + persisted: h=809339
2018-04-03 01:35:37,739 INFO  [appender-59] c.w.s.BlockchainUpdaterImpl - Block(4e99qJCpTaZ8eSoa2ucfBUYjacXCmU9xZag6t3jdR1GcTk3k9QkYHDkG9otuU24cL63HVvigfU38jnnzbgzQKUKE -> cRntkXo..., txs=7, features=Set()) appended. New height: 809546)
2018-04-03 01:35:37,739 DEBUG [rx-score-observer-55] c.w.n.RxScoreObserver$ - New local score: 107846505213269567289044, old: 107846212407808079835844, Δ292805461487453200
2018-04-03 01:35:37,742 INFO  [appender-59] c.w.s.BlockchainUpdaterImpl - After block application, total persisted blocks: 809546, [ in-memory: (Δh=99, Δtxs=3438) | (Δh=108, Δtxs=5979) ] + persisted: h=809339
2018-04-03 01:35:37,743 INFO  [appender-59] c.w.s.BlockchainUpdaterImpl - Block(3Wh8Wtx6ytAAfe3VnjC1rxRd2dfU9S9k9nXGkp5gskmwGUCqTKXL1bij9YTzDJnqnirGp9waFawS1hLzkXuf34TD -> 4e99qJC..., txs=2, features=Set()) appended. New height: 809547)
2018-04-03 01:35:37,743 DEBUG [rx-score-observer-55] c.w.n.RxScoreObserver$ - New local score: 107846823260581182970968, old: 107846505213269567289044, Δ318047311615681924
2018-04-03 01:35:37,756 DEBUG [appender-59] c.w.state2.StateWriterImpl - Starting persist from 809339 to 809447
2018-04-03 01:35:38,577 DEBUG [nio-worker-group-3-1] c.w.n.PeerDatabaseImpl - Suspending [055dd215 160.16.235.65:6868]
```
the waves process also stopped so I restart waves process after changing JAVA_OPTS  in ` /etc/default/waves`

```
# Waves node environment file
JAVA_OPTS="-Xms1024M -Xmx3480M"
```
