### ISSUE TITLE
Error while initializing actor system wavesplatform

### ISSUE THREAD

**Issue by cr1x56** [wavesplatform/Waves#979]
After following the instructions on [here](https://github.com/wavesplatform/Waves/wiki/Creating-a-private-Waves-blockchain-network)

I have this error: 
 ERROR [main] c.w.actor.RootActorSystem$ - Error while initializing actor system wavesplatform
java.lang.Exception: Could not load any of the factory classes: org.fusesource.leveldbjni.JniDBFactory, org.iq80.leveldb.impl.Iq80DBFactory
        at com.wavesplatform.db.LevelDBFactory$.$anonfun$load$5(LevelDBFactory.scala:29)
        at scala.Option.getOrElse(Option.scala:121)
        at com.wavesplatform.db.LevelDBFactory$.load(LevelDBFactory.scala:29)
        at com.wavesplatform.db.LevelDBFactory$.factory$lzycompute(LevelDBFactory.scala:9)
        at com.wavesplatform.db.LevelDBFactory$.factory(LevelDBFactory.scala:9)
        at com.wavesplatform.db.package$.openDB(package.scala:23)
        at com.wavesplatform.Application.<init>(Application.scala:58)
        at com.wavesplatform.Application$.$anonfun$main$3(Application.scala:379)
        at com.wavesplatform.Application$.$anonfun$main$3$adapted(Application.scala:353)
        at com.wavesplatform.actor.RootActorSystem$.start(RootActorSystem.scala:25)
        at com.wavesplatform.Application$.main(Application.scala:353)
        at com.wavesplatform.Application.main(Application.scala)

Using sbt 1.1.2 &  waves release 0.10.3

Tried using the custom config and the precompiled release as well as following the instructions to get compile. Both fails with same error.

**Comment by cr1x56** [comment]
Issue was fixed by changing java version
